import {test,expect,afterEach} from 'bun:test';
import {mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {initializeConfig} from '../src/apps/workspace-hub/lib/config.mjs';
import {contextView,bindContext,collectContext,packet,applyContext,reviewMap,saveDraft,requestAnalysis,contextMap,contextTick,discardPacket} from '../src/apps/workspace-hub/lib/context-engine.mjs';
import {pages,gmailEvidence,catalog,orgPages} from '../src/apps/workspace-hub/lib/context-sources.mjs';
import {startSetup} from '../src/apps/workspace-hub/lib/setup-server.mjs';
// Synthetic fixtures are isolated in tests, never seeded into an installation.
const dirs=[];afterEach(async()=>{for(const d of dirs.splice(0))await rm(d,{recursive:true,force:true});});
const at='2026-09-01T12:00:00Z';
const binding=()=>({userId:'user-a',organizationId:'org-a',containers:[],artifacts:[],sessions:[],projects:['native-a'],tasks:[],agentId:'agent-a',gmail:{connectorId:'',account:'',labels:[],query:''},focus:'Work',days:15});
const identity={authenticated:true,session:{consoleUrl:'https://console.ravi.bot',user:{id:'user-a'},organization:{id:'org-a',name:'Test organization'}}};
const paginated=(items,args)=>({items,pagination:{total:items.length,offset:Number(args[args.indexOf('--offset')+1]),returned:items.length,hasMore:false}});
function runner({org='org-a',summary='Objective from registry',deny=false,send}={}){return async args=>{
 if(args[0]==='whoami')return {...identity,session:{...identity.session,organization:{id:org}}};
 if(args[0]==='sessions'&&args[1]==='send'){if(send)return send(args);return {accepted:true};}
 if(args[0]==='sessions')return 'All sessions (0 returned of 0, limit 100, offset 0)';
 if(args[0]==='projects'){if(deny)throw Error('ACCESS_DENIED');return paginated([{id:'native-a',title:'Test initiative',summary,updatedAt:at,status:'active'}],args);}
 if(args[0]==='agents')return paginated([{id:'agent-a',name:'Test agent'}],args);
 if(args[0]==='tasks')return {items:[],page:{hasMore:false}};
 if(args[0]==='cloud')return paginated([{id:'container-a',orgId:'org-a',name:'Container'}],args);
 if(args[0]==='connectors')return {connections:[],pagination:{total:0,offset:0,returned:0}};
 if(args[0]==='artifacts')return paginated([],args);
 throw Error('UNSUPPORTED_FIXTURE');
 };}
async function installation(options={}){const dir=await mkdtemp(join(tmpdir(),'context-test-'));dirs.push(dir);const file=join(dir,'config.json');await initializeConfig(file);const run=runner(options),inventory=await catalog(15,run),v=await contextView(file);await bindContext(file,{revision:v.revision,binding:binding()},inventory,{run});return {file,run,inventory};}
const patch=p=>({batchId:p.id,baseHash:p.baseHash,decisions:p.evidence.map(e=>({id:e.id,disposition:'use',reason:'Explicit native initiative'})),projects:[{id:'project-a',title:'Test initiative',client:'',objective:'Work',summary:'Grounded context',stage:'Recorded',actions:['Review scope'],gaps:['No delivery evidence'],evidence:p.evidence.map(e=>e.id),status:'proposed'}]});
test('new install maps native resources without pipeline, Gmail or conversations',async()=>{const {file,run}=await installation();const r=await collectContext(file,{run});expect(r.status).toBe('review_required');const p=await packet(file);expect(p.evidence).toHaveLength(1);expect(p.evidence[0].level).toBe('registry');expect((await applyContext(file,patch(p))).status).toBe('applied');expect((await contextView(file)).projects).toHaveLength(1);});
test('same evidence is unchanged and does not move synthesis date',async()=>{const {file,run}=await installation();await collectContext(file,{run});await applyContext(file,patch(await packet(file)));const before=await contextView(file);expect((await collectContext(file,{run})).status).toBe('unchanged');expect((await contextView(file)).synthesizedAt).toBe(before.synthesizedAt);});
test('a source failure preserves map, fingerprints and synthesis date',async()=>{const {file,run}=await installation();await collectContext(file,{run});await applyContext(file,patch(await packet(file)));const before=await contextView(file);const r=await collectContext(file,{run:runner({deny:true})});expect(r.status).toBe('source_error');expect(r.projects).toEqual(before.projects);expect(r.synthesizedAt).toBe(before.synthesizedAt);expect(r.coverage.projects.error).toBe('SOURCE_UNAVAILABLE');});
test('organization change rejects collection before reading source content',async()=>{const {file}=await installation();const before=await readFile(file+'.context.json','utf8');await expect(collectContext(file,{run:runner({org:'org-b'})})).rejects.toThrow('ORGANIZATION_CHANGED');expect(await readFile(file+'.context.json','utf8')).toBe(before);});
test('unobserved source cannot be injected through browser selection',async()=>{const {file,run,inventory}=await installation();await expect(bindContext(file,{revision:(await contextView(file)).revision,binding:{...binding(),projects:['not-visible']}},inventory,{run})).rejects.toThrow('UNOBSERVED_SELECTION');});
test('every evidence needs a decision; unknown evidence cannot ground a claim',async()=>{const {file,run}=await installation();await collectContext(file,{run});const p=await packet(file),x=patch(p);x.decisions=[];await expect(applyContext(file,x)).rejects.toThrow('INCOMPLETE_REVIEW');const y=patch(p);y.projects[0].evidence=['unknown'];await expect(applyContext(file,y)).rejects.toThrow('UNGROUNDED_CONTEXT');expect((await contextView(file)).projects).toEqual([]);});
test('batch application is idempotent and stale base is rejected',async()=>{const {file,run}=await installation();await collectContext(file,{run});const p=await packet(file);await expect(applyContext(file,{...patch(p),baseHash:'wrong'})).rejects.toThrow('ANALYSIS_CONFLICT');await applyContext(file,patch(p));expect((await applyContext(file,patch(p))).status).toBe('already_applied');});
test('backend views and applied state omit email/document sampled text',async()=>{const {file,run}=await installation({summary:'PRIVATE_BODY_SENTINEL'});await collectContext(file,{run});expect(JSON.stringify(await contextView(file))).not.toContain('PRIVATE_BODY_SENTINEL');await applyContext(file,patch(await packet(file)));expect(await readFile(file+'.context.json','utf8')).not.toContain('PRIVATE_BODY_SENTINEL');});
test('rename survives new evidence while current summary can evolve',async()=>{const {file,run}=await installation();await collectContext(file,{run});await applyContext(file,patch(await packet(file)));let v=await contextView(file);v.projects[0].title='User correction';await reviewMap(file,{revision:v.revision,projects:v.projects});v=await contextView(file);await reviewMap(file,{revision:v.revision,projects:v.projects});await collectContext(file,{run:runner({summary:'New explicit update'})});const x=patch(await packet(file));x.projects[0].summary='New grounded summary';await applyContext(file,x);const p=(await contextView(file)).projects[0];expect(p.title).toBe('User correction');expect(p.summary).toBe('New grounded summary');});
test('excluded source cannot create a duplicate project in a later review',async()=>{const {file,run}=await installation();await collectContext(file,{run});await applyContext(file,patch(await packet(file)));const v=await contextView(file);await reviewMap(file,{revision:v.revision,projects:[]});await collectContext(file,{run:runner({summary:'New version'})});const x=patch(await packet(file));x.projects[0].id='project-duplicate';await expect(applyContext(file,x)).rejects.toThrow('HUMAN_ASSOCIATION_CONFLICT');expect((await contextView(file)).projects).toEqual([]);});
test('draft saves without changing the active binding or map',async()=>{const {file}=await installation();const v=await contextView(file);const saved=await saveDraft(file,{revision:v.revision,draft:{step:3,binding:{...binding(),focus:'draft only'}}});expect(saved.binding.focus).toBe('Work');expect(saved.draft.binding.focus).toBe('draft only');await expect(saveDraft(file,{revision:v.revision,draft:{step:3,binding:binding()}})).rejects.toThrow('CONFIG_CHANGED');});
test('ambiguous submission is not retried or reported as analysis complete',async()=>{const {file,run}=await installation();await collectContext(file,{run});let calls=0;const r=runner({send:()=>{calls++;throw Error('NETWORK_ERROR');}});expect((await requestAnalysis(file,{run:r})).status).toBe('submission_unconfirmed');expect((await requestAnalysis(file,{run:r})).status).toBe('submission_unconfirmed');expect(calls).toBe(1);expect((await contextView(file)).projects).toEqual([]);});
test('Gmail requires the explicitly selected account and read capabilities',async()=>{const b={connectorId:'google-a',account:'a@example.test',labels:[],query:''};await expect(gmailEvidence(b,15,async()=>({connection:{id:'google-a',status:'active',externalAccountLogin:'b@example.test',capabilities:[]}}))).rejects.toThrow('GMAIL_ACCOUNT_MISMATCH');await expect(gmailEvidence(b,15,async()=>({connection:{id:'google-a',status:'active',externalAccountLogin:b.account,capabilities:[]}}))).rejects.toThrow('GMAIL_READ_SCOPE_REQUIRED');});
test('Gmail cursor dedup, labels, bounded excerpts and dates; no send or mutations',async()=>{const calls=[],b={connectorId:'google-a',account:'a@example.test',labels:['INBOX'],query:'subject:scope'};let lists=0;
 const out=await gmailEvidence(b,15,async args=>{calls.push(args);if(args[0]==='connectors')return {connection:{id:b.connectorId,status:'active',externalAccountLogin:b.account,capabilities:['gmail.message.read','gmail.message.list']}};if(args[1]==='list')return {result:{messages:[{id:'m1',threadId:'t1'}],...(lists++===0?{nextPageToken:'next'}:{})}};return {result:{id:'m1',internalDate:String(Date.now()),headers:{subject:'A real subject in a fixture'},body:{text:'X'.repeat(5000)}}};});
 expect(out.items).toHaveLength(1);expect(out.complete).toBe(true);expect(out.items[0].text.length).toBeLessThan(1601);expect(calls.filter(x=>x[1]==='read')).toHaveLength(1);expect(calls[1]).toContain('INBOX');expect(calls.every(x=>!x.includes('send'))).toBe(true);
});
test('catalog pagination rejects duplicate records and count drift',async()=>{await expect(pages(['pages','list','x'],async args=>({items:[{id:'duplicate'},{id:'duplicate'}],pagination:{total:2,returned:2,offset:0,hasMore:false}}))).rejects.toThrow('INCOMPLETE_CATALOG');});
test('private Pages discovery rejects a project from another organization',async()=>{await expect(orgPages({...binding(),containers:['other']},runner())).rejects.toThrow('UNOBSERVED_SELECTION');});
test('metadata alone cannot create an apparently understood project',async()=>{const {file,run}=await installation();await collectContext(file,{run});const s=JSON.parse(await readFile(file+'.context.json'));s.pending.evidence[0].level='metadata';await writeFile(file+'.context.json',JSON.stringify(s));await expect(applyContext(file,patch(await packet(file)))).rejects.toThrow('INSUFFICIENT_CONTENT');});
test('expired or ambiguous batch can be explicitly discarded; late patch is refused',async()=>{const {file,run}=await installation();await collectContext(file,{run});const p=await packet(file),s=JSON.parse(await readFile(file+'.context.json'));s.pending.expiresAt='2000-01-01T00:00:00Z';await writeFile(file+'.context.json',JSON.stringify(s));await expect(applyContext(file,patch(p))).rejects.toThrow('ANALYSIS_EXPIRED');const v=await contextView(file);await discardPacket(file,{revision:v.revision});await expect(applyContext(file,patch(p))).rejects.toThrow('NO_PENDING_ANALYSIS');expect((await contextView(file)).pending).toBeNull();});
test('a scope change does not reuse the previous map',async()=>{const {file,run,inventory}=await installation();await collectContext(file,{run});await applyContext(file,patch(await packet(file)));const v=await contextView(file);await bindContext(file,{revision:v.revision,binding:{...binding(),projects:[]}},inventory,{run});expect((await contextView(file)).projects).toEqual([]);expect(JSON.parse(await readFile(file+'.context.json.previous')).projects).toHaveLength(1);});
test('periodic collection respects the opt out and cadence without another job',async()=>{const {file,run}=await installation();expect((await contextTick(file,{run})).status).toBe('not_configured');await collectContext(file,{run});await applyContext(file,patch(await packet(file)));const v=await contextView(file);await reviewMap(file,{revision:v.revision,projects:v.projects});expect((await contextTick(file,{run})).status).toBe('not_due');});
test('switching Console accounts hides the previous map in the web view',async()=>{const {file,run}=await installation();await collectContext(file,{run});await applyContext(file,patch(await packet(file)));const server=await startSetup(file,{contextRun:runner({org:'org-b'})});const origin='http://127.0.0.1:'+server.port;try{const html=await (await fetch(origin)).text();expect(html).not.toContain('Grounded context');const nonce=html.match(/workspaceSetupNonce="([a-f0-9]+)"/)[1];const v=await (await fetch(origin+'/context/view',{method:'POST',headers:{origin,'Content-Type':'application/json','x-workspace-setup':nonce},body:'{}'})).json();expect(v.scopeChanged).toBe(true);expect(v.projects).toEqual([]);expect(v.binding).toBeNull();}finally{server.stop(true);}});
test('HTTP guide refuses cross-origin changes and does not expose a packet endpoint',async()=>{const {file,run}=await installation();const server=await startSetup(file,{contextRun:run});const origin='http://127.0.0.1:'+server.port;try{const html=await (await fetch(origin)).text();expect(html).toContain('context-guide');expect(html).not.toContain('Grounded context');const nonce=html.match(/workspaceSetupNonce="([a-f0-9]+)"/)[1];expect((await fetch(origin+'/context/view',{method:'POST',headers:{origin:'http://evil.test','Content-Type':'application/json','x-workspace-setup':nonce},body:'{}'})).status).toBe(403);expect((await fetch(origin+'/context/packet',{method:'POST',headers:{origin,'Content-Type':'application/json','x-workspace-setup':nonce},body:'{}'})).status).toBe(404);}finally{server.stop(true);}});
