import {test,expect,afterEach} from 'bun:test';
import {mkdtemp,writeFile,readFile,chmod,symlink,rm,realpath} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {DEFAULT_CONFIG,readConfig} from '../src/apps/workspace-hub/lib/config.mjs';
import {emptyPresentation} from '../src/apps/workspace-hub/lib/snapshot.mjs';
import {privateRead,privateWrite,operationLock} from '../src/apps/workspace-hub/lib/operation-storage.mjs';
import {prepareOperation,loadOperation,refreshOperation,scheduleOperation,operationStatus} from '../src/apps/workspace-hub/lib/operations.mjs';
import {paginated} from '../src/apps/workspace-hub/lib/operation-native.mjs';
const roots=[];
afterEach(async()=>{for(const p of roots.splice(0))await rm(p,{recursive:true,force:true});});
async function fixture(){
 const root=await realpath(await mkdtemp(join(tmpdir(),'workspace-op-')));roots.push(root);
 const config={...structuredClone(DEFAULT_CONFIG),installationId:randomUUID(),sources:['projects'],selection:{...structuredClone(DEFAULT_CONFIG.selection),projects:['project-test']}};
 const file=join(root,'input.json');await writeFile(file,JSON.stringify(config),{mode:0o600});
 const state={principal:'agent_identity:test-one',agentId:'test-one',user:'user-one',members:1,sites:[],jobs:[],calls:[],failPublish:false,expired:false,adds:0};
 const run=async args=>{
  state.calls.push(args);
  if(args[0]==='self')return {identity:{kind:'turn-runtime',agentId:state.agentId,sessionKey:'test-session',source:{accountId:'test-account'},expiresAt:Date.now()+(state.expired?-1:3600000),metadata:{agentIdentityPrincipal:state.principal}}};
  if(args[0]==='whoami')return {authenticated:true,session:{user:{id:state.user}}};
  if(args[0]==='pages'&&args[1]==='create'){state.sites.push({id:'site-one',slug:args[3],projectId:'project-one',defaultVisibility:'private',createdByActorType:'user',createdByActorId:state.user,activeReleaseId:null});return {success:true};}
  if(args[0]==='pages'&&args[1]==='publish'){if(state.failPublish)throw Error('SOURCE_UNAVAILABLE');state.sites[0].activeReleaseId='release-one';return {success:true,release:{id:'release-one'}};}
  if(args[0]==='cron'&&args[1]==='add'){
   state.adds++;const get=f=>args[args.indexOf(f)+1];const job={id:'job-one',name:args[2],agentId:get('--agent'),accountId:get('--account'),replySession:'test-session',sessionTarget:'isolated',executionType:'agent',message:get('--message'),description:get('--description'),schedule:{type:'every',every:900000},enabled:true,deleteAfterRun:false};state.jobs.push(job);if(state.failAdd)throw Error('SOURCE_UNAVAILABLE');return {job};
  }
  if(args[0]==='cron'&&args[1]==='show')return {job:state.jobs.find(j=>j.id===args[2])};
  const items=args[0]==='cloud'?[{id:'project-one',slug:'test-project',members:state.members}]:args[0]==='pages'?state.sites:args[0]==='cron'?state.jobs:null;
  if(!items)throw Error('UNEXPECTED_COMMAND');
  const offset=Number(args[args.indexOf('--offset')+1]),limit=Number(args[args.indexOf('--limit')+1]),page=items.slice(offset,offset+limit);
  return {items:page,pagination:{offset,total:items.length,returned:page.length,hasMore:offset+page.length<items.length,nextOffset:offset+page.length<items.length?offset+page.length:null}};
 };
 const collector=async file=>{
  const c=JSON.parse(await readFile(file,'utf8')),at=new Date().toISOString(),presentation=emptyPresentation(c);delete presentation.sourceStates;
  presentation.home.projects=[{id:'project-test',title:'Isolated test fixture',status:'active',summary:'Fixture only'}];
  await privateWrite(file+'.snapshot.json',{schema:'workspace.snapshot/v1',installationId:c.installationId,capturedAt:at,presentation,sourceStates:{projects:{status:'ready',capturedAt:at}}});
  return {status:'collected',results:{projects:{status:'ready'}}};
 };
 const prepared=await prepareOperation(file,join(root,'operations'),'project-one',{run});
 return {root,file,config,dir:prepared.directory,state,run,collector};
}
test('preparation is stable, private and contains no runtime lease',async()=>{const f=await fixture();const again=await prepareOperation(f.file,join(f.root,'operations'),'project-one',{run:f.run});expect(again.status).toBe('existing');expect(await readFile(join(f.dir,'operation.json'),'utf8')).not.toMatch(/contextId|expiresAt/);expect((await operationStatus(f.dir,{run:f.run})).publishedAt).toBeNull();});
test('runtime principal change blocks managed config and collection',async()=>{const f=await fixture();f.state.principal='agent_identity:another';await expect(readConfig(join(f.dir,'config.json'),{identityRunner:f.run})).rejects.toThrow('INSTALLATION_IDENTITY_MISMATCH');await expect(refreshOperation(f.dir,{run:f.run,collector:f.collector})).rejects.toThrow('INSTALLATION_IDENTITY_MISMATCH');expect(f.state.calls.some(a=>a[1]==='publish')).toBe(false);});
test('expired turn fails without creating a new context',async()=>{const f=await fixture();f.state.expired=true;await expect(loadOperation(f.dir,f.run)).rejects.toThrow('LIVE_AGENT_IDENTITY_REQUIRED');expect(f.state.calls.some(a=>a[0]==='context')).toBe(false);});
test('Console user change blocks before source reads',async()=>{const f=await fixture();f.state.user='user-two';let reads=0;await expect(refreshOperation(f.dir,{run:f.run,collector:async()=>{reads++;}})).rejects.toThrow('CONSOLE_IDENTITY_MISMATCH');expect(reads).toBe(0);});
test('membership growth preserves valid generation',async()=>{const f=await fixture();await refreshOperation(f.dir,{run:f.run,collector:f.collector});const before=await readFile(join(f.dir,'current.json'),'utf8');await privateWrite(join(f.dir,'last-attempt.json'),{at:'2020-01-01T00:00:00Z'});f.state.members=2;await expect(refreshOperation(f.dir,{publish:true,run:f.run,collector:f.collector})).rejects.toThrow('PRIVATE_MEMBERSHIP_NOT_CONFIRMED');expect(await readFile(join(f.dir,'current.json'),'utf8')).toBe(before);});
test('refresh builds shell and cadence skips duplicate reads',async()=>{const f=await fixture();let reads=0;const collector=async file=>{reads++;return f.collector(file);};const r=await refreshOperation(f.dir,{run:f.run,collector});expect(r.status).toBe('collected');const html=await readFile(join(f.dir,'generations',r.generation,'index.html'),'utf8');expect(html).toContain('Home');expect(html).toContain('Isolated test fixture');expect(html).not.toContain('agent_identity:');expect((await refreshOperation(f.dir,{run:f.run,collector})).status).toBe('not_due');expect(reads).toBe(1);});
test('two directories do not share cache or accept swapped configuration',async()=>{const a=await fixture(),b=await fixture();await refreshOperation(a.dir,{run:a.run,collector:a.collector});expect(await privateRead(join(b.dir,'current.json'),{optional:true})).toBeNull();const swapped=JSON.parse(await readFile(join(a.dir,'config.json'),'utf8'));await privateWrite(join(b.dir,'config.json'),swapped);await expect(loadOperation(b.dir,b.run)).rejects.toThrow('OPERATION_REVIEW_REQUIRED');});
test('symlink and world-readable storage rejected',async()=>{const f=await fixture();await chmod(join(f.dir,'config.json'),0o644);await expect(loadOperation(f.dir,f.run)).rejects.toThrow('PRIVATE_STORAGE_REQUIRED');await chmod(join(f.dir,'config.json'),0o600);const alias=join(f.root,'alias');await symlink(f.dir,alias);await expect(loadOperation(alias,f.run)).rejects.toThrow('UNSAFE_STORAGE_PATH');});
test('parallel refresh lock is not stolen',async()=>{const f=await fixture();await operationLock(f.dir,async()=>{await expect(refreshOperation(f.dir,{run:f.run,collector:f.collector})).rejects.toThrow('OPERATION_ALREADY_RUNNING');});expect(await privateRead(join(f.dir,'current.json'),{optional:true})).toBeNull();});
test('failed source keeps snapshot, generation and original date',async()=>{const f=await fixture();await refreshOperation(f.dir,{run:f.run,collector:f.collector});const paths=['config.json.snapshot.json','current.json'];const before=await Promise.all(paths.map(p=>readFile(join(f.dir,p),'utf8')));await privateWrite(join(f.dir,'last-attempt.json'),{at:'2020-01-01T00:00:00Z'});await expect(refreshOperation(f.dir,{run:f.run,collector:async()=>({results:{projects:{status:'unavailable'}}})})).rejects.toThrow('NO_CONFIRMED_SOURCE');expect(await Promise.all(paths.map(p=>readFile(join(f.dir,p),'utf8')))).toEqual(before);expect((await operationStatus(f.dir,{run:f.run})).lastAttempt.error).toBe('NO_CONFIRMED_SOURCE');});
test('foreign snapshot never reaches current or publish',async()=>{const f=await fixture();await expect(refreshOperation(f.dir,{publish:true,run:f.run,collector:async file=>{await f.collector(file);const s=await privateRead(file+'.snapshot.json');s.installationId='another-installation';await privateWrite(file+'.snapshot.json',s);return {results:{projects:{status:'ready'}}};}})).rejects.toThrow();expect(await privateRead(join(f.dir,'current.json'),{optional:true})).toBeNull();expect(f.state.sites).toHaveLength(0);});
test('publication retry reuses pending bytes and idempotency key',async()=>{const f=await fixture();f.state.failPublish=true;await expect(refreshOperation(f.dir,{publish:true,run:f.run,collector:f.collector})).rejects.toThrow('SOURCE_UNAVAILABLE');expect(await privateRead(join(f.dir,'published.json'),{optional:true})).toBeNull();expect(await privateRead(join(f.dir,'pending.json'))).toBeTruthy();f.state.failPublish=false;expect((await refreshOperation(f.dir,{publish:true,run:f.run,collector:async()=>{throw Error('MUST_NOT_RECOLLECT');}})).status).toBe('published_private');const publishes=f.state.calls.filter(a=>a[0]==='pages'&&a[1]==='publish');expect(publishes[0][publishes[0].indexOf('--idempotency-key')+1]).toBe(publishes[1][publishes[1].indexOf('--idempotency-key')+1]);expect(publishes.every(a=>a[a.indexOf('--visibility')+1]==='private')).toBe(true);});
test('foreign public site is not overwritten',async()=>{const f=await fixture();const p=await privateRead(join(f.dir,'operation.json'));f.state.sites=[{id:'other',slug:p.site,projectId:p.project.id,defaultVisibility:'public',createdByActorType:'user',createdByActorId:'someone'}];await expect(refreshOperation(f.dir,{publish:true,run:f.run,collector:f.collector})).rejects.toThrow('PRIVATE_SITE_OWNERSHIP_NOT_CONFIRMED');expect(f.state.calls.some(a=>a[1]==='publish')).toBe(false);});
test('schedule defaults to plan; applying twice creates only one agent cron',async()=>{const f=await fixture();expect((await scheduleOperation(f.dir,{run:f.run})).status).toBe('planned');expect(f.state.adds).toBe(0);expect((await scheduleOperation(f.dir,{run:f.run,apply:true})).status).toBe('scheduled');expect((await scheduleOperation(f.dir,{run:f.run,apply:true})).status).toBe('existing');expect(f.state.adds).toBe(1);expect(f.state.jobs[0].executionType).toBe('agent');expect(f.state.jobs[0].sessionTarget).toBe('isolated');expect(f.state.calls.some(a=>a.includes('--env-file')||a.includes('--shell'))).toBe(false);});
test('ambiguous cron creation is reconciled before retry',async()=>{const f=await fixture();f.state.failAdd=true;await expect(scheduleOperation(f.dir,{run:f.run,apply:true})).rejects.toThrow('SOURCE_UNAVAILABLE');f.state.failAdd=false;expect((await scheduleOperation(f.dir,{run:f.run,apply:true})).status).toBe('existing');expect(f.state.adds).toBe(1);f.state.jobs=[];await expect(scheduleOperation(f.dir,{run:f.run,apply:true})).rejects.toThrow('SCHEDULE_CREATION_UNCONFIRMED');expect(f.state.adds).toBe(1);});
test('duplicate or modified schedule fails without changing jobs',async()=>{const f=await fixture();await scheduleOperation(f.dir,{run:f.run,apply:true});f.state.jobs.push({...f.state.jobs[0],id:'duplicate'});await expect(scheduleOperation(f.dir,{run:f.run,apply:true})).rejects.toThrow('DUPLICATE_SCHEDULE');f.state.jobs.pop();f.state.jobs[0].agentId='wrong';await expect(scheduleOperation(f.dir,{run:f.run,apply:true})).rejects.toThrow('SCHEDULE_CONFLICT');expect(f.state.adds).toBe(1);});
test('pagination verifies complete count',async()=>{let calls=0;const rows=await paginated(['cron','list'],async a=>{calls++;const offset=Number(a[a.indexOf('--offset')+1]);return {items:[{id:String(offset)}],pagination:{total:2,offset,returned:1,hasMore:offset===0,nextOffset:offset===0?1:null}};});expect(rows).toHaveLength(2);expect(calls).toBe(2);await expect(paginated(['cron','list'],async()=>({items:[],pagination:{total:1,offset:0,returned:0,hasMore:false}}))).rejects.toThrow('INCOMPLETE_INVENTORY');});
test('explicit publish after review uses the prepared generation without new reads',async()=>{const f=await fixture();const first=await refreshOperation(f.dir,{run:f.run,collector:f.collector});const result=await refreshOperation(f.dir,{publish:true,run:f.run,collector:async()=>{throw Error('UNEXPECTED_RECOLLECTION');}});expect(result.hash).toBe(first.generation);expect(result.status).toBe('published_private');expect((await refreshOperation(f.dir,{publish:true,run:f.run,collector:f.collector})).status).toBe('not_due');});
test('corrupt pending path is rejected before reading or publishing bytes',async()=>{const f=await fixture();await privateWrite(join(f.dir,'pending.json'),{hash:'../../outside',htmlHash:'invalid',capturedAt:new Date().toISOString()});await expect(refreshOperation(f.dir,{publish:true,run:f.run,collector:f.collector})).rejects.toThrow('INVALID_GENERATION');expect(f.state.calls.some(a=>a[1]==='publish')).toBe(false);});
