import {test,expect,afterAll} from 'bun:test';
import {mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {initializeConfig,readConfig} from '../src/apps/workspace-hub/lib/config.mjs';
import {configure,setupView,saveSetup,collect,readSnapshot,importSnapshot,atomic,snapshotPath} from '../src/apps/workspace-hub/lib/setup.mjs';
import {discover,nativeRows,sessionRows} from '../src/apps/workspace-hub/lib/native.mjs';
import {dayBounds,calendar,meetings,setting} from '../src/apps/workspace-hub/lib/providers.mjs';
import {startSetup} from '../src/apps/workspace-hub/lib/setup-server.mjs';
import {emptyPresentation} from '../src/apps/workspace-hub/lib/snapshot.mjs';
const root=await mkdtemp(join(tmpdir(),'workspace-setup-test-'));afterAll(()=>rm(root,{recursive:true,force:true}));
const now=()=>new Date().toISOString();
const inventory=()=>({capturedAt:now(),agents:[{id:'agent-test',name:'Test agent'}],sessions:[{id:'session-test',name:'Test session',agent:'agent-test'}],projects:[{id:'project-test',title:'Test project'}],tasks:[],coverage:Object.fromEntries(['agents','sessions','projects','tasks'].map(k=>[k,{status:'ready'}]))});
async function installation(){const dir=await mkdtemp(join(root,'case-'));const file=join(dir,'config.json');await initializeConfig(file);return {file,config:await readConfig(file)};}
const input=(c,i=inventory())=>{const v=setupView(c,i,null);return {revision:v.revision,workspaceName:'Selected workspace',selection:{...c.selection,agents:['agent-test'],sessions:['session-test'],projects:['project-test']},sources:['agents','projects','tasks']};};
test('setup view never exposes asset paths or credentials',async()=>{const {config}=await installation();config.brand.logoFile='/private/asset.png';const v=setupView(config,inventory(),null);expect(JSON.stringify(v)).not.toContain('/private/asset');expect(v.selectionIsPermission).toBe(false);});
test('unknown selection and mismatched agent are rejected before saving',async()=>{const {config}=await installation();const value=input(config);value.selection.projects=['unseen'];expect(()=>configure(config,value,inventory())).toThrow('UNOBSERVED_SELECTION');value.selection.projects=[];value.selection.agents=[];expect(()=>configure(config,value,inventory())).toThrow('SESSION_AGENT_REQUIRED');});
test('stale inventory and config revisions fail closed',async()=>{const {config}=await installation();const i=inventory();i.capturedAt='2020-01-01T00:00:00Z';expect(()=>configure(config,input(config),i)).toThrow('INVENTORY_EXPIRED');expect(()=>configure(config,{...input(config),revision:'old'},inventory())).toThrow('CONFIG_CHANGED');});
test('save persists selection but does not claim access or collect data',async()=>{const {file,config}=await installation();const result=await saveSetup(file,input(config),inventory());expect(result.sourcesVerified).toBe(false);expect(await readSnapshot(file)).toBe(null);expect((await readConfig(file)).selection.agents).toEqual(['agent-test']);});
test('invalid timezone preserves config bytes',async()=>{const {file,config}=await installation();const old=await readFile(file,'utf8');await expect(saveSetup(file,{...input(config),timezone:'invalid'},inventory())).rejects.toThrow();expect(await readFile(file,'utf8')).toBe(old);});
test('native collection uses explicit selection and records actual source dates',async()=>{const {file,config}=await installation();await saveSetup(file,input(config),inventory());const r=await collect(file,{inventoryLoader:async()=>inventory()});const s=await readSnapshot(file);expect(r.status).toBe('collected');expect(s.presentation.agents.map(a=>a.id)).toEqual(['agent-test']);expect(s.presentation.home.projects).toHaveLength(1);expect(s.sourceStates.tasks.status).toBe('ready');});
test('provider/native failure keeps last valid records and their date',async()=>{const {file,config}=await installation();await saveSetup(file,input(config),inventory());await collect(file,{inventoryLoader:async()=>inventory()});const before=await readSnapshot(file);const bad=inventory();Object.values(bad.coverage).forEach(v=>v.status='unavailable');await collect(file,{inventoryLoader:async()=>bad});const after=await readSnapshot(file);expect(after.presentation.home.projects).toEqual(before.presentation.home.projects);expect(after.sourceStates.projects.status).toBe('stale');expect(after.sourceStates.projects.capturedAt).toBe(before.sourceStates.projects.capturedAt);});
test('confirmed native empty removes stale records',async()=>{const {file,config}=await installation();await saveSetup(file,input(config),inventory());await collect(file,{inventoryLoader:async()=>inventory()});await collect(file,{inventoryLoader:async()=>({...inventory(),projects:[]})});expect((await readSnapshot(file)).presentation.home.projects).toEqual([]);});
test('malformed provider response cannot replace a valid feed',async()=>{const {file,config}=await installation();config.sources=['agenda'];config.integrations.agenda={mode:'google-workspace',account:'test@example.invalid'};await atomic(file,config);await collect(file,{inventoryLoader:async()=>inventory(),calendarLoader:async()=>({status:'ready',items:[{id:'a',title:'bad'}]})});expect((await readSnapshot(file)).sourceStates.agenda.status).toBe('unavailable');});
test('expired access preserves valid calendar; account change requires review',async()=>{
 const {file,config}=await installation();config.sources=['agenda'];config.integrations.agenda={mode:'google-workspace',account:'test@example.invalid'};await atomic(file,config);
 const feed={status:'ready',source:'Test calendar',capturedAt:now(),date:'2026-09-09',items:[{id:'event',title:'Test appointment',start:'2026-09-09',end:'2026-09-10',allDay:true,url:''}]};
 await collect(file,{inventoryLoader:async()=>inventory(),calendarLoader:async()=>feed});
 await collect(file,{inventoryLoader:async()=>inventory(),calendarLoader:async()=>{throw Error('AUTH_EXPIRED')}});
 const s=await readSnapshot(file);expect(s.sourceStates.agenda.status).toBe('stale');expect(s.presentation.home.feeds.agenda.items).toEqual(feed.items);expect(s.sourceStates.agenda.capturedAt).toBe(feed.capturedAt);
 const c=await readConfig(file),before=await readFile(file,'utf8');await expect(saveSetup(file,{...input(c),integrations:{...c.integrations,agenda:{mode:'google-workspace',account:'other@example.invalid'}}},inventory())).rejects.toThrow('SOURCE_CHANGE_REQUIRES_REVIEW');expect(await readFile(file,'utf8')).toBe(before);
});
test('import refuses another installation and transcript contents',async()=>{const {file,config}=await installation();const {sourceStates,...presentation}=emptyPresentation(config);const s={schema:'workspace.snapshot/v1',installationId:'another-installation',capturedAt:now(),presentation,sourceStates};await expect(importSnapshot(file,s)).rejects.toThrow('SNAPSHOT_INSTALLATION_MISMATCH');s.installationId=config.installationId;s.presentation.transcript='isolated test';await expect(importSnapshot(file,s)).rejects.toThrow();expect(await readSnapshot(file)).toBe(null);});
test('parallel operations do not overwrite a held setup lock',async()=>{const {file,config}=await installation();await writeFile(file+'.setup.lock','test');await expect(saveSetup(file,input(config),inventory())).rejects.toThrow('SETUP_BUSY');expect((await readConfig(file)).sources).toEqual([]);});
test('native pagination rejects duplicate IDs and unstable counts',async()=>{await expect(nativeRows('projects',15,async()=>({items:[{id:'same'},{id:'same'}],pagination:{hasMore:false,total:2,offset:0,returned:2}}))).rejects.toThrow('INVALID_NATIVE_ID');});
test('denial yields unavailable inventory, never fabricated successful zero',async()=>{const d=await discover(15,async()=>{throw Error('ACCESS_DENIED')});expect(d.agents).toEqual([]);expect(d.coverage.agents.status).toBe('unavailable');});
test('credential patterns in native labels fail before reaching setup',async()=>{const d=await discover(15,async args=>args[0]==='sessions'?'invalid table':{items:[{id:'native',title:'ghp_'+'x'.repeat(40),name:'ghp_'+'x'.repeat(40)}],pagination:{hasMore:false,total:1,offset:0,returned:1},page:{hasMore:false}});expect(d.agents).toEqual([]);expect(d.coverage.agents.error).toBe('SENSITIVE_SOURCE_CONTENT');});
test('session table only extracts metadata and excludes evaluations',async()=>{const table='All sessions (2 returned of 2, limit 100, offset 0):\n  session-test  agent-test  1k  now  permanent  -  -  Test session\n  eval-test  agent-test  1k  now  permanent  -  -  Eval\n';const rows=await sessionRows(async()=>table);expect(rows).toHaveLength(1);expect(rows[0].name).toBe('Test session');expect(Object.keys(rows[0])).not.toContain('runtime');});
test('changed table headers are rejected rather than guessed',async()=>{await expect(sessionRows(async()=>'changed header')).rejects.toThrow('SESSION_METADATA_CONTRACT_CHANGED');});
test('civil calendar boundaries include DST transitions',()=>{const a=dayBounds('America/New_York',new Date('2026-03-08T12:00:00Z'));expect(a.from).toBe('2026-03-08T05:00:00.000Z');expect(a.through).toBe('2026-03-09T04:00:00.000Z');const b=dayBounds('America/Sao_Paulo',new Date('2026-09-09T02:00:00Z'));expect(b.date).toBe('2026-09-08');});
test('calendar verifies expected identity before reading events',async()=>{const {config}=await installation();config.integrations.agenda={mode:'google-workspace',account:'owner@example.invalid'};let count=0;await expect(calendar(config,{read:async()=> 'test-value',get:async url=>{count++;return url.includes('token')?{access_token:'test-token'}:{id:'different@example.invalid'}}})).rejects.toThrow('ACCOUNT_MISMATCH');expect(count).toBe(2);});
test('calendar excludes declined/cancelled events and deduplicates pages',async()=>{const {config}=await installation();config.integrations.agenda={mode:'google-workspace',account:'owner@example.invalid'};let p=0;const good={id:'event-test',summary:'Unit event',start:{date:'2026-09-09'},end:{date:'2026-09-10'},htmlLink:'https://calendar.google.com'};const result=await calendar(config,{read:async()=> 'test',now:new Date('2026-09-09T12:00:00Z'),get:async url=>url.includes('token')?{access_token:'test-token'}:!url.includes('/events?')?{id:'owner@example.invalid'}:++p===1?{items:[good,{...good,id:'cancel',status:'cancelled'},{...good,id:'declined',attendees:[{self:true,responseStatus:'declined'}]}],nextPageToken:'next'}:{items:[good]}});expect(result.items).toHaveLength(1);expect(result.items[0].id).toBe('event-test');expect(JSON.stringify(result)).not.toContain('test-token');});
test('missing credential never falls back to another setting',async()=>{await expect(setting('test.key',async()=> 'invalid response')).rejects.toThrow('CREDENTIAL_UNAVAILABLE');});
test('meetings skip missing and empty transcripts; never return raw segments',async()=>{const {config}=await installation();const stamp=now();const list=[1,2,3].map(n=>({id:'m'+n,name:'Test '+n,happenedAt:stamp,url:'https://tldv.io/app/meetings'}));const feed=await meetings(config,{read:async()=> 'test-key',get:async url=>{if(url.includes('?'))return {results:list,pages:1};if(url.includes('/m1/'))throw Error('NOT_FOUND');return {meetingId:url.includes('/m2/')?'m2':'m3',data:url.includes('/m2/')?[]:[{text:'Never copied to frontend'}]};}});expect(feed.items).toHaveLength(1);expect(feed.items[0].id).toBe('m3');expect(JSON.stringify(feed)).not.toContain('Never copied');expect(feed.items[0].analysis).toBeUndefined();});
test('transcript identity mismatch fails the complete meeting read',async()=>{const {config}=await installation();await expect(meetings(config,{read:async()=> 'test-key',get:async url=>url.includes('?')?{results:[{id:'m',happenedAt:new Date(Date.now()-1000).toISOString()}],pages:1}:{meetingId:'other',data:[]}})).rejects.toThrow('PROVIDER_CONTRACT_CHANGED');});
test('HTTP setup rejects foreign origin and unknown nonce; cancel performs no write',async()=>{
 const {file}=await installation();const before=await readFile(file,'utf8');const server=await startSetup(file,{inventoryLoader:async()=>inventory()});const origin='http://127.0.0.1:'+server.port;
 try{const html=await (await fetch(origin)).text();const nonce=html.match(/workspaceSetupNonce="([a-f0-9]+)"/)[1];
  expect((await fetch(origin+'/setup/save',{method:'POST',headers:{Origin:'https://untrusted.invalid','Content-Type':'application/json','X-Workspace-Setup':nonce},body:'{}'})).status).toBe(403);
  expect((await fetch(origin+'/setup/save',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:'{}'})).status).toBe(403);
  expect((await fetch(origin+'/setup/discover',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','X-Workspace-Setup':nonce},body:'{}'})).status).toBe(200);
  expect((await fetch(origin+'/config.json')).status).toBe(404);expect(await readFile(file,'utf8')).toBe(before);
 }finally{server.stop(true);}
});
test('first access guides empty installations; configured data is not treated as first use',async()=>{
 const {file,config}=await installation();const server=await startSetup(file,{inventoryLoader:async()=>inventory()});
 const bootstrap=async()=>{const html=await (await fetch('http://127.0.0.1:'+server.port)).text();return JSON.parse(html.match(/window.workspaceSetupBootstrap=(\{[^;]+\});/)[1]);};
 try{
  expect(await bootstrap()).toEqual({installationId:config.installationId,firstRun:true,needsCollection:false});
  await saveSetup(file,input(config),inventory());
  expect((await bootstrap()).firstRun).toBe(false);expect((await bootstrap()).needsCollection).toBe(true);
  await collect(file,{inventoryLoader:async()=>inventory()});expect((await bootstrap()).needsCollection).toBe(false);
 }finally{server.stop(true);}
});
test('collection reports selected records, including confirmed empty sources',async()=>{
 const {file,config}=await installation();await saveSetup(file,input(config),inventory());
 const r=await collect(file,{inventoryLoader:async()=>({...inventory(),projects:[...inventory().projects,{id:'not-selected',title:'Unselected test'}]})});
 expect(r.results.projects.count).toBe(1);expect(r.results.agents.count).toBe(1);expect(r.results.tasks.count).toBe(0);
});
