import {test,expect,afterEach} from 'bun:test';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createUpdates,updatePlan} from '../src/apps/workspace-hub/lib/updates.mjs';
import {createEventStream,streamFetch} from '../src/apps/workspace-hub/lib/sdk-events.mjs';
import {parseSse} from '../src/apps/workspace-hub/vendor/ravi-sdk/streaming.js';
import {initializeConfig,readConfig} from '../src/apps/workspace-hub/lib/config.mjs';
import {atomic,collect,readSnapshot} from '../src/apps/workspace-hub/lib/setup.mjs';
import {discover} from '../src/apps/workspace-hub/lib/native.mjs';
import {startSetup} from '../src/apps/workspace-hub/lib/setup-server.mjs';
import {bindContext,collectContext,contextView} from '../src/apps/workspace-hub/lib/context-engine.mjs';

const cleanups=[];afterEach(async()=>{for(const fn of cleanups.splice(0).reverse())await fn();});
const delay=ms=>new Promise(r=>setTimeout(r,ms));
function events(){const consumers=[];return {consumers,open(subject,{signal,onOpen}){const queue=[];let wake;const end=()=>wake?.();signal.addEventListener('abort',end,{once:true});const entry={subject,push(v){queue.push(v);wake?.();}};consumers.push(entry);return (async function*(){onOpen();while(!signal.aborted){if(!queue.length)await new Promise(r=>wake=r);if(signal.aborted)break;while(queue.length){const v=queue.shift();if(v instanceof Error)throw v;yield v;}}})();}};}
function updater(extra={}){let time=1000;const calls=[],bus=events();const u=createUpdates({plan:{all:['feed:tasks','context:pages'],streams:[{subject:'ravi.task.*.event',targets:()=>['feed:tasks']}]},open:bus.open,refresh:async keys=>{calls.push(keys);},now:()=>time,debounceMs:0,minRefreshMs:0,loopMs:100000,reconcileMs:100,...extra});cleanups.push(async()=>{u.stop();await u.done();});return {u,calls,bus,advance:n=>time+=n};}
const frame=(id,topic='ravi.task.task-a.event')=>({id:String(id),data:{type:'event',topic,data:{privateBody:'DO_NOT_FORWARD'}}});
test('burst and duplicate events trigger one selected refresh, never forward content',async()=>{const {u,calls,bus}=updater();await u.flush();calls.length=0;bus.consumers[0].push(frame(1));bus.consumers[0].push(frame(1));bus.consumers[0].push(frame(2));await delay(1);await u.flush();expect(calls).toEqual([['feed:tasks']]);expect(JSON.stringify(u.status())).not.toContain('DO_NOT_FORWARD');});
test('a connection-local sequence gap reconciles all selected sources',async()=>{const {u,calls,bus}=updater();await u.flush();calls.length=0;bus.consumers[0].push(frame(4));bus.consumers[0].push(frame(6));await delay(1);await u.flush();expect(new Set(calls[0])).toEqual(new Set(['feed:tasks','context:pages']));});
test('silent lost events are reconciled periodically',async()=>{const {u,calls,advance}=updater();await u.flush();calls.length=0;advance(101);await u.tick();expect(calls).toHaveLength(1);expect(calls[0]).toHaveLength(2);});
test('events arriving during an in-flight refresh are retained, single flight',async()=>{let finish,active=0,max=0,count=0;const {u,bus}=updater({refresh:async()=>{active++;max=Math.max(max,active);count++;if(count===1)await new Promise(r=>finish=r);active--;}});const pending=u.flush();await delay(1);bus.consumers[0].push(frame(1));await delay(1);await u.flush();finish();await pending;expect(u.status().pending).toBe(1);await u.flush();expect(max).toBe(1);expect(count).toBe(2);});
test('reconnect resets duplicate IDs and reconciles after missing events',async()=>{const {u,calls,bus}=updater({retryBaseMs:1});await u.flush();bus.consumers[0].push(frame(9));bus.consumers[0].push(Error('SOURCE_UNAVAILABLE'));await delay(10);await u.flush();expect(bus.consumers).toHaveLength(2);calls.length=0;bus.consumers[1].push(frame(1));await delay(1);await u.flush();expect(calls).toEqual([['feed:tasks']]);});
for(const code of ['ACCESS_DENIED','AUTH_EXPIRED','SDK_OPERATION_UNAVAILABLE'])test(code+' stream does not reconnect or use a CLI fallback',async()=>{let opens=0;const {u}=updater({retryBaseMs:1,open:async function*(){opens++;throw Error(code);}});await delay(10);expect(opens).toBe(1);expect(u.status().unavailable).toBe(1);});
test('reconnect exhaustion is bounded and cancellation stops retry timers',async()=>{let n=0;const {u}=updater({retryBaseMs:1,maxRetries:2,open:async function*(){n++;throw Error('SOURCE_UNAVAILABLE');}});await delay(20);expect(n).toBe(3);expect(u.status().unavailable).toBe(1);u.stop();await delay(10);expect(n).toBe(3);});
test('busy lock retains invalidation; failed read preserves last success date',async()=>{let count=0;const {u,advance}=updater({refresh:async()=>{if(++count===1)throw Error('SETUP_BUSY');if(count===3)throw Error('SOURCE_UNAVAILABLE');}});await u.flush();expect(u.status().pending).toBe(2);await u.flush();const at=u.status().lastSuccess;advance(101);await u.tick();expect(u.status().lastSuccess).toBe(at);expect(u.status().status).toBe('stale');});
test('minimum refresh interval limits continuous bursts',async()=>{const {u,calls,advance}=updater({minRefreshMs:100});await u.flush();u.invalidate(['feed:tasks']);await u.flush();expect(calls).toHaveLength(1);advance(101);await u.flush();expect(calls).toHaveLength(2);});
test('stopping during read cannot publish a successful revision',async()=>{let finish;const {u}=updater({refresh:()=>new Promise(r=>finish=r)});const p=u.flush();u.stop();finish();await p;expect(u.status().revision).toBe(0);});
test('scope plan groups only selected task/artifact/session identifiers and respects opt out',()=>{const c={sources:['tasks'],selection:{tasks:['task-a']}},b={autoUpdate:true,containers:['container-a'],artifacts:['artifact-a'],sessions:['selected-session'],projects:[],tasks:[],gmail:{connectorId:'gmail-a'}};
 const p=updatePlan(c,b,true);expect(p.streams[0].targets(frame(1,'ravi.task.other.event').data)).toEqual([]);expect(p.streams[1].targets({topic:'ravi.artifacts.completed',data:{artifactId:'other'}})).toEqual([]);expect(p.streams.some(s=>s.subject==='ravi.session.selected-session.response')).toBe(true);expect(p.streams[1].targets({topic:'ravi.artifacts.completed',data:{version:1,eventType:'artifact.lifecycle',artifact:{id:'artifact-a'}}})).toEqual(['context:artifact:artifact-a']);expect(p.all).toContain('context:gmail');expect(updatePlan(c,{...b,autoUpdate:false},true).all).toEqual(['feed:tasks']);expect(updatePlan(c,b,false).all).toEqual(['feed:tasks']);});

test('official SDK SSE handles split UTF-8/CRLF and drops heartbeat frames',async()=>{const bytes=new TextEncoder().encode(': ping\r\n\r\nid: 1\r\ndata: {"type":"event","topic":"ravi.task.a.event","text":"ação"}\r\n\r\n');let i=0;
 const f=streamFetch(async()=>new Response(new ReadableStream({pull(c){i<bytes.length?c.enqueue(bytes.slice(i,i+=1)):c.close();}}),{headers:{'content-type':'text/event-stream'}}));const out=[];for await(const e of parseSse((await f('http://test')).body))out.push(e);expect(out).toHaveLength(1);expect(out[0].data.text).toBe('ação');});
test('oversized or truncated SSE frames fail closed',async()=>{for(const raw of ['data: '+ 'x'.repeat(200),'data: {}']){const f=streamFetch(async()=>new Response(raw,{headers:{'content-type':'text/event-stream'}}),{maxFrameBytes:100});await expect((async()=>{for await(const e of parseSse((await f('http://test')).body)){} })()).rejects.toThrow();}});
test('SDK SSE sends inherited credential server-side and uses an exact backend subject',async()=>{let request;const open=createEventStream({baseUrl:'http://127.0.0.1:1234',contextKey:'test-only-context',fetchImpl:async(url,init)=>{request={url,init};return new Response('data: {"type":"event","topic":"ravi.task.a.event","data":{}}\n\n',{headers:{'content-type':'text/event-stream'}});}});for await(const e of open('ravi.task.*.event',{signal:new AbortController().signal,onOpen(){}}))expect(e.data.type).toBe('event');expect(request.init.headers.authorization).toBe('Bearer test-only-context');expect(new URL(request.url).searchParams.get('subject')).toBe('ravi.task.*.event');expect(request.init.redirect).toBe('error');});
for(const status of [401,403,404])test('SSE HTTP '+status+' is explicit and not parsed as an event',async()=>{const f=streamFetch(async()=>new Response('not a stream',{status}));await expect(f('http://test')).rejects.toThrow(status===401?'AUTH_EXPIRED':status===403?'ACCESS_DENIED':'SDK_OPERATION_UNAVAILABLE');});

async function installation(){const dir=await mkdtemp(join(tmpdir(),'workspace-events-test-'));cleanups.push(()=>rm(dir,{recursive:true,force:true}));const file=join(dir,'config.json'),created=await initializeConfig(file),config=await readConfig(file);return {file,config};}
const inventory=()=>({capturedAt:new Date().toISOString(),historyDays:15,agents:[],sessions:[],projects:[{id:'project-a',title:'Project A'}],tasks:[{id:'task-a',title:'Task A'}],coverage:Object.fromEntries(['agents','sessions','projects','tasks'].map(k=>[k,{status:'ready'}]))});
test('targeted feed collection does not touch calendar, other rows or their dates',async()=>{const {file,config}=await installation();config.sources=['projects','tasks','agenda'];config.selection.projects=['project-a'];config.selection.tasks=['task-a'];await atomic(file,config);await collect(file,{inventoryLoader:async()=>inventory()});const old=await readSnapshot(file);let options;
 await collect(file,{sources:['tasks'],inventoryLoader:async(d,r,o)=>{options=o;return {...inventory(),tasks:[]};},calendarLoader:async()=>{throw Error('UNEXPECTED_CALL');}});const next=await readSnapshot(file);expect(options.kinds).toEqual(['tasks']);expect(next.presentation.home.projects).toEqual(old.presentation.home.projects);expect(next.sourceStates.projects).toEqual(old.sourceStates.projects);expect(next.sourceStates.agenda).toEqual(old.sourceStates.agenda);expect(next.presentation.home.tasks).toEqual([]);});
test('native targeted inventory executes only requested operation',async()=>{const calls=[];await discover(15,async args=>{calls.push(args[0]);throw Error('ACCESS_DENIED');},{kinds:['tasks']});expect(calls).toEqual(['tasks']);});
test('failed final scope verification preserves snapshot bytes',async()=>{const {file,config}=await installation();config.sources=['projects'];config.selection.projects=['project-a'];await atomic(file,config);await collect(file,{inventoryLoader:async()=>inventory()});const before=await readFile(file+'.snapshot.json','utf8');let n=0;await expect(collect(file,{sources:['projects'],inventoryLoader:async()=>inventory(),verify:async()=>{if(++n===2)throw Error('ORGANIZATION_CHANGED');}})).rejects.toThrow('ORGANIZATION_CHANGED');expect(await readFile(file+'.snapshot.json','utf8')).toBe(before);});
test('local HTTP update is nonce/origin protected and returns sanitized presentation, not stream data',async()=>{const {file,config}=await installation();const bus=events();const server=await startSetup(file,{eventOpen:bus.open,updateOptions:{loopMs:100000},inventoryLoader:async()=>inventory()});cleanups.push(()=>server.stop(true));const origin='http://127.0.0.1:'+server.port;const html=await (await fetch(origin)).text(),nonce=html.match(/workspaceSetupNonce="([a-f0-9]+)"/)[1];
 expect((await fetch(origin+'/updates')).status).toBe(404);expect((await fetch(origin+'/updates',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:'{}'})).status).toBe(403);
 const post=body=>fetch(origin+'/updates',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','X-Workspace-Setup':nonce},body:JSON.stringify(body)});
 const result=await (await post({})).json();expect(result.installationId).toBe(config.installationId);expect(result.data).toBeDefined();expect(result).not.toHaveProperty('contextKey');expect(result).not.toHaveProperty('topic');expect((await (await post({revision:result.revision})).json()).data).toBeUndefined();
});

test('SSE header timeout covers a fetch that ignores abort',async()=>{const f=streamFetch(()=>new Promise(()=>{}),{headerMs:15});await expect(f('http://test')).rejects.toThrow('SDK_TIMEOUT');});
test('SSE idle timeout cancels stalled body after headers',async()=>{let cancelled=false;const f=streamFetch(async()=>new Response(new ReadableStream({cancel(){cancelled=true;}}),{headers:{'content-type':'text/event-stream'}}),{idleMs:15});await expect((async()=>{for await(const e of parseSse((await f('http://test')).body)){} })()).rejects.toThrow('SDK_TIMEOUT');expect(cancelled).toBe(true);});
test('targeted context change does not re-read unrelated selected sources or claim synthesis',async()=>{
 const {file}=await installation(),calls=[];
 const run=async args=>{calls.push(args.slice(0,2).join('.'));if(args[0]==='whoami')return {authenticated:true,session:{consoleUrl:'https://console.ravi.bot',user:{id:'user-a'},organization:{id:'org-a'}}};if(args[0]==='tasks')return {items:[{id:'task-a',title:'Task with clear objective',status:'open'}],page:{hasMore:false}};throw Error('UNEXPECTED_SOURCE');};
 const binding={userId:'user-a',organizationId:'org-a',containers:['container-a'],artifacts:['artifact-a'],sessions:['session-a'],projects:['project-a'],tasks:['task-a'],agentId:'agent-a',gmail:{connectorId:'',account:'',labels:[],query:''},focus:'Work',days:15,autoUpdate:true};
 const inventory={capturedAt:new Date().toISOString(),account:{userId:'user-a',organization:{id:'org-a'}},containers:[{id:'container-a'}],artifacts:[{id:'artifact:artifact-a'}],native:{sessions:[{id:'session-a'}],projects:[{id:'project-a'}],tasks:[{id:'task-a'}],agents:[{id:'agent-a',role:'Agente Ravi'}]},connections:[]};
 await bindContext(file,{revision:(await contextView(file)).revision,binding},inventory,{run});calls.length=0;
 const result=await collectContext(file,{run,kinds:['tasks']});expect(result.status).toBe('review_required');expect(result.synthesizedAt).toBe(null);expect(calls).toEqual(['whoami.--json','tasks.list','whoami.--json']);expect(result.pending.count).toBe(1);
});

test('event → targeted collection → snapshot → HTTP UI; denial keeps last valid Task and date',async()=>{
 const {file,config}=await installation();config.sources=['tasks','projects'];config.selection.tasks=['task-a'];config.selection.projects=['project-a'];await atomic(file,config);
 let title='First task',deny=false;const bus=events();const loader=async()=>{const r=inventory();r.tasks=[{id:'task-a',title}];if(deny)r.coverage.tasks={status:'unavailable'};return r;};
 const server=await startSetup(file,{inventoryLoader:loader,eventOpen:bus.open,updateOptions:{debounceMs:0,minRefreshMs:0,loopMs:5}});cleanups.push(()=>server.stop(true));
 const origin='http://127.0.0.1:'+server.port,html=await (await fetch(origin)).text(),nonce=html.match(/workspaceSetupNonce="([a-f0-9]+)"/)[1];
 const poll=async()=>await (await fetch(origin+'/updates',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','X-Workspace-Setup':nonce},body:'{}'})).json();
 const until=async fn=>{for(let n=0;n<150;n++){if(await fn())return;await delay(5);}throw Error('TEST_REFRESH_TIMEOUT');};
 await poll();await until(async()=>!!(await readSnapshot(file))?.sourceStates.tasks.capturedAt);
 const first=await readSnapshot(file);title='Second task';bus.consumers[0].push(frame(1));await until(async()=>(await readSnapshot(file))?.presentation.home.tasks[0]?.title===title);
 const second=await readSnapshot(file);expect((await poll()).data.home.tasks[0].title).toBe('Second task');expect(second.sourceStates.projects).toEqual(first.sourceStates.projects);
 deny=true;bus.consumers[0].push(frame(2));await until(async()=>(await readSnapshot(file))?.sourceStates.tasks.status==='stale');
 const final=await readSnapshot(file);expect(final.presentation.home.tasks).toEqual(second.presentation.home.tasks);expect(final.sourceStates.tasks.capturedAt).toBe(second.sourceStates.tasks.capturedAt);expect(JSON.stringify(await poll())).not.toContain('DO_NOT_FORWARD');
});
