  let alertsData=data.alerts;
  let alertsHasRunHistory=alertsData.items.some(item=>item.lastStatus!==null||item.lastRunAt!==null);
  const alertsFilters=[['all','Todos'],['active','Ativos'],['paused','Pausados'],['failed','Com falha']];
  let alertAgents=[...new Map(alertsData.items.map(item=>[item.agentKey,{id:item.agentKey,name:item.agentName}])).values()].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));
  const alertsCapture=()=>AlertsModel.date(Date.parse(alertsData.capturedAt));
  const alertCount=(status)=>alertsData.items.filter(item=>AlertsModel.matches(item,{status})).length;
  function readAlertFilters(params){return {query:(params.get('q')||'').slice(0,200),status:alertsFilters.some(([id])=>id===params.get('status'))?params.get('status'):'all',agent:alertAgents.some(a=>a.id===params.get('agent'))?params.get('agent'):'all'};}
  function alertBadge(item){const state=AlertsModel.state(item);return label(state==='active'?'Ativo':state==='paused'?'Pausado':'Estado não informado',state==='active'?'green':'');}
  function alertsCoverage(){return alertsData.coverage.status==='complete'?`<div class="alerts-coverage coverage-complete">${icon('check')}<div><strong>Inventário consultado</strong><p>${e(alertsCapture())} · ${e(config.timezone)}. Os horários refletem esta consulta.</p></div><button data-action="alerts-source">Ver origem ${icon('arrow')}</button></div>`:`<div class="alerts-coverage">${icon('info')}<div><strong>O inventário dos seus agentes ainda está incompleto.</strong><p>A consulta disponível não confirma os agendamentos dos demais agentes. Nenhum cron visível nesta captura não significa ausência de crons no seu workspace.</p></div><button data-action="alerts-source">Entender o alcance ${icon('arrow')}</button></div>`;}
  function alertRow(item){
    const active=AlertsModel.state(item)==='active';
    return link(`/alerts/${item.id}`,`<span class="alert-row-icon">${icon(item.schedule.type==='at'?'calendar':'clock')}</span><div class="alert-row-copy"><div class="alert-row-title"><h3>${e(item.name)}</h3>${alertBadge(item)}</div><p>${e(AlertsModel.schedule(item))}${item.schedule.type==='cron'?` · ${e(item.schedule.timezone||'Fuso não informado')}`:''}</p><small>${AlertsModel.finite(item.lastRunAt)?`Última execução: ${e(AlertsModel.date(item.lastRunAt))}`:'Sem execução informada'}${AlertsModel.isFailed(item)?' · Último resultado com falha':item.lastStatus==='ok'?' · Último resultado OK':''}</small></div><div class="alert-row-next"><span>Próximo disparo</span><strong>${active?e(AlertsModel.date(item.nextRunAt)):AlertsModel.state(item)==='paused'?'Pausado':'Não informado'}</strong></div>${icon('arrow')}`,'alert-row',`alert-${item.id}`);
  }
  function alertResults(filters){
    const items=AlertsModel.sort(alertsData.items.filter(item=>AlertsModel.matches(item,filters)));
    const filtered=!!filters.query||filters.status!=='all'||filters.agent!=='all';
    if(filters.status==='failed'&&alertsData.items.length&&!alertsHasRunHistory)return `<div class="alerts-empty"><h2>Histórico de execução indisponível</h2><p>A consulta de agendamentos não informa o último resultado. Não é possível identificar falhas com estes dados.</p><button class="secondary" data-action="alerts-clear">Ver agendamentos</button></div>`;
    if(!items.length){
      if(alertsData.items.length&&filtered)return `<div class="alerts-empty"><span class="alerts-empty-icon">${icon('search')}</span><h2>Nenhum agendamento corresponde aos filtros.</h2><p>Experimente outro nome, agente ou estado.</p><button class="secondary" data-action="alerts-clear">Limpar filtros</button></div>`;
      return `<div class="alerts-empty"><div class="alerts-empty-emblem" aria-hidden="true"><span>${icon('alerts')}</span></div><span class="tiny-label">${alertsData.coverage.status==='complete'?'Consulta concluída':'Aguardando inventário completo'}</span><h2>${alertsData.coverage.status==='complete'?'Nenhum agendamento neste inventário.':'Seus agendamentos, em um só lugar.'}</h2><p>${alertsData.coverage.status==='complete'?'Não há crons cadastrados no escopo verificado nesta captura.':'Alerts reunirá os crons dos seus Ravis: o que está ativo, quando dispara e como foi a última execução. A consulta atual não tornou nenhum deles visível.'}</p><button class="secondary" data-action="alerts-source">${icon('info')}Ver origem e acesso</button><div class="alerts-reading-guide"><div>${icon('agents')}<strong>Quem cuida</strong><span>Agente responsável</span></div><div>${icon('clock')}<strong>Quando acontece</strong><span>Frequência e próximo disparo</span></div><div>${icon('check')}<strong>Como foi</strong><span>Último resultado informado</span></div></div></div>`;
    }
    return `<p class="alerts-result-count" role="status">${items.length} ${items.length===1?'agendamento visível':'agendamentos visíveis'}${filtered?' com estes filtros':''}</p>${alertAgents.filter(a=>items.some(item=>item.agentKey===a.id)).map(a=>`<section class="alert-agent-group" aria-label="${e(a.name)}"><header><span class="avatar small-avatar">${e(a.name.slice(0,1).toUpperCase())}</span><h2>${e(a.name)}</h2><span>${items.filter(item=>item.agentKey===a.id).length} ${items.filter(item=>item.agentKey===a.id).length===1?'agendamento':'agendamentos'}</span></header><div class="alert-group-list">${items.filter(item=>item.agentKey===a.id).map(alertRow).join('')}</div></section>`).join('')}`;
  }
  function alerts(params){
    const f=readAlertFilters(params),count=alertsData.items.length;
    return `${heading('Alerts','Os agendamentos dos seus Ravis, organizados por agente.','Seu workspace')}<div class="alerts-overview"><div><span class="alerts-page-mark">${icon('alerts')}</span><span><strong>${count?`${count} agendamentos visíveis`:alertsData.coverage.status==='complete'?'Nenhum agendamento':'Visibilidade pendente'}</strong><small>Ativos e pausados · todos os agentes solicitados</small></span></div><button data-action="alerts-source">${icon('clock')}Consulta de ${e(alertsCapture())}</button></div>${nativeLiveNotice('alerts')}${alertsCoverage()}<div class="alerts-tools"><div class="alerts-search">${icon('search')}<input id="alerts-query" type="search" autocomplete="off" maxlength="200" placeholder="Buscar nome ou agente" aria-label="Buscar agendamentos" value="${e(f.query)}" data-focus-key="alerts-query"><button data-action="alerts-clear-query" aria-label="Limpar busca de agendamentos">×</button></div><label class="alerts-agent-filter"><span>Agente</span><select id="alerts-agent" data-focus-key="alerts-agent" ${alertAgents.length?'':'disabled'}><option value="all">Todos os agentes visíveis</option>${alertAgents.map(a=>`<option value="${e(a.id)}" ${a.id===f.agent?'selected':''}>${e(a.name)}</option>`).join('')}</select></label></div><div class="alerts-filterline"><div class="segments" role="group" aria-label="Filtrar agendamentos por estado">${alertsFilters.map(([id,name])=>`<button data-action="alerts-status:${id}" data-alert-status="${id}" data-focus-key="alerts-status-${id}" aria-pressed="${f.status===id}">${name}${count?`<span class="alert-filter-count">${id==='failed'&&!alertsHasRunHistory?'—':alertCount(id)}</span>`:''}</button>`).join('')}</div><span class="small muted">${alertsData.coverage.status==='complete'?'Snapshot consultado':'Cobertura parcial'}</span></div>${count&&!alertsHasRunHistory?'<p class="small muted" style="margin-bottom:18px">Histórico de execução indisponível nesta consulta. Falhas não foram verificadas.</p>':''}<div id="alerts-results">${alertResults(f)}</div><div class="alerts-bottom-note">${icon('info')}<span>Horários de disparo e execução em ${e(config.timezone)}. A consulta não executa nem altera agendamentos. ${e(alertsCapture())}.</span></div>`;
  }
  function alertDetail(id){
    const item=alertsData.items.find(i=>i.id===id);if(!item)return missing();
    const schedule=item.schedule;
    return `${back('/alerts')}${heading(item.name,'Configuração observada no inventário de agendamentos.','Alerts')}<div class="project-meta">${alertBadge(item)}<span>${e(item.agentName)}</span>${AlertsModel.isFailed(item)?label('Último resultado com falha','amber'):''}</div><section class="panel alert-detail"><h2>Quando e como acontece</h2><dl class="work-metadata"><div><dt>Frequência</dt><dd>${e(AlertsModel.schedule(item))}</dd></div><div><dt>Fuso do calendário</dt><dd>${schedule.type==='cron'?e(schedule.timezone||'Não informado'):'Não se aplica a intervalo ou horário absoluto'}</dd></div><div><dt>Próximo disparo informado</dt><dd>${item.enabled===false?'Pausado':e(AlertsModel.date(item.nextRunAt))}</dd></div><div><dt>Última execução informada</dt><dd>${e(AlertsModel.date(item.lastRunAt))}</dd></div><div><dt>Último resultado</dt><dd>${item.lastStatus==='ok'?'OK':item.lastStatus==='error'?'Falha':'Não informado'}</dd></div><div><dt>Tipo de execução</dt><dd>${item.executionType==='shell'?'Rotina automática':'Agente'}</dd></div><div><dt>Após executar</dt><dd>${item.deleteAfterRun===true?'Remover o agendamento':item.deleteAfterRun===false?'Manter o agendamento':'Não informado'}</dd></div></dl><div class="dialog-note">Horários de disparo e execução em ${e(config.timezone)}. O estado e o próximo disparo refletem a captura; não certificam execução neste momento. Falha é o último resultado registrado, não prova de falha atual.</div><button class="text-link" data-action="alerts-source">${icon('file')}Ver origem e alcance</button></section>`;
  }
  function updateAlerts(changes){
    if(parseRoute(routeFromLocation()).path!=='/alerts')return;
    const f={...readAlertFilters(parseRoute(routeFromLocation()).params),...changes};
    const params=new URLSearchParams();if(f.query)params.set('q',f.query.slice(0,200));if(f.status!=='all')params.set('status',f.status);if(f.agent!=='all')params.set('agent',f.agent);
    const route='/alerts'+(params.size?'?'+params:'');
    history.replaceState(history.state,'',`#${route}`);renderedRoute=route;
    document.querySelectorAll('[data-alert-status]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.alertStatus===f.status)));
    document.getElementById('alerts-results').innerHTML=alertResults(f);
    document.getElementById('announcer').textContent=`${alertsData.items.filter(i=>AlertsModel.matches(i,f)).length} agendamentos visíveis com estes filtros. ${alertsData.coverage.status==='complete'?'':'Inventário incompleto.'}`;
  }
  function alertsAction(name){
    if(name==='alerts-source'){
      showDialog('Alcance do inventário','Alerts · origem dos dados',`<p>Captura: ${e(alertsCapture())} · ${e(config.timezone)}.</p><p>${alertsData.items.length} registros incluídos para os agentes selecionados nesta instalação.</p><div class="dialog-note">${sourceReady('alerts')?'A consulta corresponde ao escopo informado na captura.':'A consulta atual não foi confirmada. Não é possível afirmar que estes sejam todos os agendamentos disponíveis.'} Última execução e resultado só aparecem quando fornecidos pela fonte.</div><p>Este pacote não consulta nem altera os crons. Os registros disponíveis conservam sua data.</p>`);return true;
    }
    if(name.startsWith('alerts-status:')){const status=name.slice(14);if(alertsFilters.some(([id])=>id===status))updateAlerts({status});return true;}
    if(name==='alerts-clear-query'||name==='alerts-clear'){
      const input=document.getElementById('alerts-query');if(!input)return true;input.value='';
      if(name==='alerts-clear'){document.getElementById('alerts-agent').value='all';updateAlerts({query:'',status:'all',agent:'all'});}else updateAlerts({query:''});
      input.focus();return true;
    }
    return false;
  }
  document.addEventListener('input',event=>{if(event.target.id==='alerts-query')updateAlerts({query:event.target.value});});
  document.addEventListener('change',event=>{if(event.target.id==='alerts-agent')updateAlerts({agent:event.target.value});});
