  const connectorsData=data.connectors;
  const connectorItems=connectorsData.items;
  let connectionSources=data.connectionSources||null;
  const connectorDestinations={agenda:{name:'Agenda do dia',route:'/agenda',icon:'calendar'},meetings:{name:'Reuniões transcritas',route:'/meetings',icon:'meeting'}};
  const connectorLinks=new Set(connectorItems.flatMap(c=>[c.manageUrl,c.helpUrl]));
  const connectorExternal=(url,text,cls='text-link')=>{
    if(!connectorLinks.has(url))return '';
    try{const u=new URL(url);if(u.protocol!=='https:'||u.username||u.password)return '';return `<a class="${cls}" href="${e(url)}" target="_blank" rel="noopener noreferrer">${e(text)} ${icon('external')}</a>`;}catch{return '';}
  };
  const connectorMark=c=>`<span class="connector-mark connector-mark-${c.id}" aria-hidden="true">${c.id==='tldv'?'tl;dv':icon('calendar')}</span>`;
  const connectorBinding=c=>connectionSources?.bindings.find(b=>b.feed===c.feed);
  function connectorObservation(c){
    const state=feedLiveStates[c.feed],feed=state?.data||homeData.feeds[c.feed];
    if(feedLiveExpired)return {label:'Entre novamente',color:'amber',verified:false};
    if(!navigator.onLine)return {label:'Sem conexão · última leitura',color:'amber',verified:false};
    if(state?.error||feedLiveError)return {label:'Atualização indisponível',color:'amber',verified:false};
    if(state?.refreshing)return {label:'Consultando',color:'',verified:false};
    if(!feed?.capturedAt||feed.status!=='ready')return {label:'Verificação pendente',color:'amber',verified:false};
    if(Date.now()-Date.parse(feed.capturedAt)>1200000||state?.stale)return {label:'Leitura desatualizada',color:'amber',verified:false};
    return {label:feedLiveAvailable&&state?.verified?'Leitura confirmada':'Última leitura registrada',color:state?.verified?'green':'',verified:!!state?.verified};
  }
  const connectorVerified=c=>connectorObservation(c).verified;
  const connectorBadge=c=>{const s=connectorObservation(c);return label(s.label,s.color);};
  function connectorDependencies(c){
    const dest=connectorDestinations[c.feed];
    return `<div class="connector-dependencies"><h3>Onde é usada</h3>${link(dest.route,`${icon(dest.icon)}${e(dest.name)} ${icon('arrow')}`,'connector-destination')}<p>Também aparece nos detalhes e na busca do Workspace.</p><h3>Agentes</h3>${connectionSources?.collector?.agent&&data.agents.some(a=>a.id===connectionSources.collector.agent)?`<p>${link('/agents/'+connectionSources.collector.agent,activityAgentName(connectionSources.collector.agent),'text-link')} · coleta os dados para a Home.</p>`:'<p>Coletor ainda não confirmado.</p>'}<p class="small muted">Este mapa cobre o coletor da Home. O uso direto por outros agentes não foi auditado.</p></div>`;
  }
  function connectorCard(c){
    const dest=connectorDestinations[c.feed],f=homeData.feeds[c.feed];
    return `<article class="connector-card"><header>${connectorMark(c)}${connectorBadge(c)}</header><h2>${e(c.name)}</h2><p>${e(c.purpose)}</p><div class="connector-account">${icon('agents')}<span>${e(c.account)}</span></div><div class="connector-used"><span>${connectorBinding(c)?'Fonte escolhida para a Home':'Fonte a conferir'}</span>${link(dest.route,`${icon(dest.icon)}${e(dest.name)} ${icon('arrow')}`,'connector-destination')}</div><footer><span>${f.capturedAt?`Última leitura · ${e(feedDate(f.capturedAt))}`:'Sem leitura disponível'}</span>${link(`/connectors/${c.id}`,`Gerenciar ${icon('arrow')}`,'connector-manage')}</footer></article>`;
  }
  function connectors(){
    return `${heading('Connectors','Veja de onde vêm seus dados e o que depende de cada acesso.','Seu workspace')}<div class="connectors-intro"><span class="connector-orbit" aria-hidden="true">${icon('connectors')}</span><div><strong>${connectorItems.filter(connectorVerified).length} de ${connectorItems.length} leituras confirmadas nesta atualização</strong><p>Uma conexão cadastrada só alimenta a Home quando é escolhida e validada como fonte.</p></div><button class="text-link" data-action="connectors-about">Sobre os acessos ${icon('info')}</button></div><div class="connector-grid">${connectorItems.map(connectorCard).join('')||'<section class="panel"><h2>Configure suas fontes</h2><p>Nenhuma integração foi incluída nesta instalação. Google Calendar e tl;dv podem ser adicionados ao configurar os seus acessos.</p></section>'}</div>${managerSection()}<section class="connector-file-section"><header><div><p class="eyebrow">Também no workspace</p><h2>Ravi Pages · Pipeline</h2></div>${label(feedLiveStates.pipeline?.error?'Última cópia disponível':'Fonte em arquivo',feedLiveStates.pipeline?.error?'amber':'')}</header><div class="connector-file-row"><span class="connector-file-mark">${icon('file')}</span><div><h3>${pipelineItems.length} frentes comerciais</h3><p>Revisão comercial de ${e(shortDate(pipelineData.sourceCheckedAt))} · consulta de ${e(feedDate(pipelineData.capturedAt))}.</p><p>O arquivo de origem e a consulta mantêm suas datas. Uma mudança apenas no navegador da fonte não confirma sincronização.</p></div>${link('/pipeline',`Ver pipeline ${icon('arrow')}`,'text-link')}<button class="text-link" data-action="feed-pipeline">Origem ${icon('info')}</button></div></section><section class="panel connector-platform"><h2>Dados do próprio Ravi</h2><p>Projetos, Tasks, conversas, Alerts e execução vêm das consultas nativas. São fontes distintas das contas Google e tl;dv.</p>${link('/activity','Ver cobertura e validade dos agentes','text-link')}<p class="small muted">Alerts mantém o último inventário quando a consulta não está disponível.</p></section><p class="connectors-footnote">${icon('clock')}As datas indicam a última consulta incluída no snapshot desta instalação. ${managerAvailable?'As ações dependem do modo autorizado desta sessão.':'Aqui você revisa conexões e abre os controles oficiais; alterações de conta são concluídas no provedor ou na sessão local de gerenciamento.'}</p>`;
  }
  function connectorDetail(id){
    const c=connectorItems.find(c=>c.id===id);if(!c)return missing();
    const f=homeData.feeds[c.feed];
    return `${back('/connectors')}<div class="connector-detail-heading">${connectorMark(c)}<div>${heading(c.name,c.purpose,'Connectors')}</div></div><div class="connector-detail-status">${connectorBadge(c)}<span>${f.capturedAt?`Leitura de ${e(feedDate(f.capturedAt))} · ${e(config.timezone)}`:'Sem leitura disponível'}</span></div><div class="connector-detail-grid"><section class="panel connector-access"><h2>Fonte escolhida</h2><dl class="work-metadata"><div><dt>Conta</dt><dd>${e(c.account)}</dd></div><div><dt>Identidade</dt><dd>${c.accountVerified?'Confirmada na última consulta válida':'Titular não informado pela integração'}</dd></div><div><dt>Acesso por</dt><dd>${e(c.method)} · integração existente</dd></div><div><dt>Vínculo com a Home</dt><dd>${connectorBinding(c)?'Fonte mantida pelo coletor':'Ainda não confirmado'}</dd></div></dl><h3>Uso observado</h3><ul class="connector-capabilities">${c.observedAccess.map(text=>`<li>${icon('check')}<span>${e(text)}</span></li>`).join('')}</ul><h3>Permissões concedidas</h3><p class="connector-permission-note">${e(c.permissionNote)}</p>${homeButton(`feed-${c.feed}`,'Ver origem e alcance dos dados')}${connectorDependencies(c)}</section><aside class="panel connector-management"><span class="connector-management-icon">${icon('sliders')}</span><h2>Gerenciar acesso</h2><p>${e(c.instructions)}</p>${connectorExternal(c.manageUrl,`Abrir ${c.id==='google-calendar'?'Conta Google':'ajustes do tl;dv'}`,'primary')}<p class="connector-management-note">Mudanças feitas no provedor só aparecem como verificadas aqui após uma nova consulta bem-sucedida.</p>${connectorExternal(c.helpUrl,'Ajuda oficial')}<div class="connector-impact"><h3>Se o acesso for removido</h3><p>Novas leituras de ${c.feed==='agenda'?'agenda':'reuniões'} podem falhar. Os últimos dados permanecem datados, sem indicar conexão ativa. As outras fontes continuam independentes.</p><button class="secondary" data-action="connector-impact:${c.id}">Revisar impacto</button></div><div class="connector-source-change"><h3>${c.feed==='agenda'?'Usar outra conta':'Substituir a chave'}</h3><p>${c.feed==='agenda'?'Revise uma conexão do projeto e os requisitos para uma troca sem perder a fonte atual.':'Criar ou revogar a chave acontece no tl;dv. A configuração do coletor é uma etapa separada; nenhuma chave é solicitada nesta interface.'}</p><button class="secondary" data-action="connector-plan:${c.id}">Revisar troca de fonte</button></div></aside></div>`;
  }
  function connectorChangePlan(c,candidate,inventoryCurrent=true){
    const base={current:connectorBinding(c)?.sourceId||null,canApply:false,changesSource:false};
    if(!base.current)return {...base,state:'unknown',reason:'A fonte atual precisa ser confirmada antes de preparar a troca.'};
    if(c.feed==='meetings')return {...base,state:'provider_managed',reason:'Crie a chave no tl;dv; depois o operador testa a nova credencial em memória antes de uma substituição explícita. A chave atual permanece selecionada.'};
    if(candidate&&!inventoryCurrent)return {...base,state:'inventory_stale',reason:'A consulta desta conexão perdeu a validade. Atualize o inventário antes de preparar a troca.'};
    if(!candidate)return {...base,state:'no_candidate',reason:'Não há outra conta Google selecionada nesta revisão. Criar uma conexão não a torna fonte da agenda automaticamente.'};
    if(candidate.provider!=='google'||candidate.status!=='active'||candidate.requiresReauth)return {...base,state:'unavailable',reason:'Esta conexão não está pronta: confira sua autorização no provedor antes de revisar uma troca.'};
    if(!candidate.scopes.some(s=>['https://www.googleapis.com/auth/calendar.readonly','https://www.googleapis.com/auth/calendar'].includes(s)))return {...base,state:'scope_missing',reason:'As permissões retornadas não confirmam a leitura necessária do calendário. Não alteramos os acessos.'};
    return {...base,state:'verification_required',reason:'A conta está cadastrada, mas ainda falta uma leitura validada pelo coletor. O contrato atual não oferece troca automática para esta conexão.'};
  }
  function connectorPlanDialog(c,id){
    const candidates=managerState.connections.filter(n=>n.provider==='google'),candidate=candidates.find(n=>n.id===id),plan=connectorChangePlan(c,candidate,!managerError&&!feedLiveExpired&&!feedLiveError&&Date.now()-Date.parse(managerState.capturedAt)<1200000);
    showDialog('Revisão da troca de fonte',c.name,`<p>Fonte atual: <strong>${e(c.account)}</strong>. Ela permanece escolhida durante esta revisão.</p>${c.feed==='agenda'&&candidates.length?`<div class="connector-candidates"><h3>Conexões cadastradas</h3>${candidates.map(n=>`<button class="secondary" data-action="connector-candidate:${n.id}">${e(n.account||n.name)} · ${e(n.status)}</button>`).join('')}</div>`:''}${candidate?`<p>Conta em revisão: <strong>${e(candidate.account||candidate.name)}</strong></p>`:''}<div class="dialog-note" data-change-state="${plan.state}">${e(plan.reason)}</div><h3>Antes de trocar</h3><ol><li>Confirmar conta, permissões e os dados retornados pela nova fonte.</li><li>Comparar a captura com o widget atual e revisar o impacto na coleta da instalação.</li><li>Confirmar a substituição explicitamente, mantendo a última captura válida e um caminho de retorno.</li></ol><p class="small muted">${feedPagesMode?'Esta Page não executa a troca no coletor. ':''}Esta revisão não conecta, revoga ou substitui acessos.</p><div class="dialog-actions"><button class="secondary" data-action="close-dialog">Cancelar revisão</button>${c.feed==='agenda'&&!candidates.length?'<button class="text-link" data-action="manager-connect">Revisar nova conexão Google</button>':''}</div>`);
  }
  function connectorLiveApply(payload){
    const state=payload.feeds.connections,raw=state?.data;
    if(raw&&(!connectionSources||Date.parse(raw.capturedAt)>=Date.parse(connectionSources.capturedAt))){connectionSources=raw;if(!managerWorking&&!managerPoll&&(!managerAvailable||Date.parse(raw.capturedAt)>=Date.parse(managerState.capturedAt||0)))managerState={project:raw.project,capturedAt:raw.capturedAt,connections:raw.connections,actionsEnabled:managerAvailable&&managerState.actionsEnabled};}
    if(!managerAvailable)managerError=state?.error?'O inventário não pôde ser atualizado. Mantivemos a última consulta.':'';
  }
  function connectorsAction(name){
    if(managerAction(name))return true;
    if(name.startsWith('connector-plan:')){const c=connectorItems.find(c=>c.id===name.slice(15));if(c)connectorPlanDialog(c);return true;}
    if(name.startsWith('connector-candidate:')){connectorPlanDialog(connectorItems.find(c=>c.feed==='agenda'),name.slice(20));return true;}
    if(name.startsWith('connector-impact:')){const c=connectorItems.find(c=>c.id===name.slice(17));if(c)showDialog('Impacto da remoção',c.name,`${connectorDependencies(c)}<div class="dialog-note">Sem este acesso, novas leituras podem falhar. A Home mantém os últimos dados com aviso e data. Remover o acesso não apaga cópias anteriores nem altera as outras fontes.</div><p>Uso por outros agentes não confirmado; revise esse alcance antes de remover no provedor.</p><button class="secondary" data-action="close-dialog">Fechar revisão</button>`);return true;}
    if(name!=='connectors-about')return false;
    showDialog('Conexões e fontes','Connectors','<p>As contas usadas pela Home estão identificadas por fonte. O inventário do projeto mostra conexões cadastradas, que podem ainda não ser usadas por nenhum widget.</p><p>Leitura confirmada informa que a consulta funcionou naquele horário. Não certifica todos os acessos concedidos nem o uso por outros agentes.</p><p>Você pode revisar impacto e troca de fonte aqui. A Page privada não recebe senhas ou chaves e não executa alterações nas contas.</p>');return true;
  }
