(()=>{
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const dialog=document.createElement('dialog');dialog.className='context-guide';dialog.setAttribute('aria-labelledby','guide-title');document.body.append(dialog);
 const titles=['Sua organização','Suas fontes','O que acompanhar','Revise seu mapa','Seu Workspace'];
 let state,inventory,binding,step=1,previousFocus,working=false,request=0,poll=null,edits=[];
 const button=(action,label,primary=false)=>`<button type="button" data-guide="${action}" class="${primary?'guide-primary':''}">${label}</button>`;
 const errors={CONSOLE_LOGIN_REQUIRED:'Entre no Ravi Console para reconhecer sua organização.',ORGANIZATION_CHANGED:'A conta ou organização mudou. Consulte as fontes novamente antes de continuar.',INVENTORY_EXPIRED:'Consulte as fontes novamente: a seleção ficou antiga.',GMAIL_READ_SCOPE_REQUIRED:'A conexão Google não confirmou acesso de leitura ao Gmail.',GMAIL_ACCOUNT_MISMATCH:'A conta Gmail consultada difere do e-mail escolhido.',CONFIG_CHANGED:'Outra janela alterou a configuração. Reabra o assistente.',ANALYSIS_EXPIRED:'Esta análise expirou. A última versão válida foi mantida. Seu Ravi pode inspecionar o lote antes de uma nova análise.',ANALYSIS_PENDING:'Aguarde a análise antes de salvar correções.',UNOBSERVED_AGENT:'Escolha um agente disponível nesta instalação.'};
 async function api(action,body={}){const r=await fetch('/context/'+action,{method:'POST',headers:{'Content-Type':'application/json','X-Workspace-Setup':window.workspaceSetupNonce},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'SOURCE_UNAVAILABLE');return d;}
 function notice(text,error=false){const n=dialog.querySelector('.guide-notice');if(n){n.textContent=text;n.classList.toggle('guide-error',error);}}
 function draw(body,footer){
  dialog.innerHTML=`<div class="guide-heading"><div><span class="guide-eyebrow">Seu contexto, no seu Ravi</span><h2 id="guide-title" tabindex="-1">${titles[step-1]}</h2></div><button data-guide="close" aria-label="Fechar assistente">×</button></div><ol class="guide-progress" aria-label="Etapas">${titles.map((t,i)=>`<li ${step===i+1?'aria-current="step"':''}><span>${i+1}</span><small>${t}</small></li>`).join('')}</ol><div class="guide-body">${body}<p class="guide-notice" role="status" aria-live="polite"></p></div><div class="guide-footer">${footer}</div>`;
  dialog.querySelector('#guide-title').focus({preventScroll:true});
  if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&window.workspaceMotion?.enter)window.workspaceMotion.enter([dialog.querySelector('.guide-body')]);
 }
 function selection(name,rows,values){return `<details class="guide-source"><summary>${name} <small>${rows.length} disponíveis</small></summary><div class="guide-scroll">${rows.map(x=>`<label class="guide-choice"><input type="checkbox" data-list="${x.list}" value="${esc(x.id)}" ${values.includes(x.id)?'checked':''}><span>${esc(x.title||x.name)}${x.summary?`<small>${esc(x.summary.slice(0,160))}</small>`:''}</span></label>`).join('')||'<p>Nenhum registro retornou nesta consulta.</p>'}</div></details>`;}
 function saveInputs(){
  if(step===2){for(const k of ['containers','artifacts','sessions','projects','tasks'])binding[k]=[...dialog.querySelectorAll(`[data-list="${k}"]:checked`)].map(el=>el.value);binding.gmail.connectorId=dialog.querySelector('#guide-gmail').value;binding.gmail.account=dialog.querySelector('#guide-account').value.trim();}
  if(step===3){binding.days=Number(dialog.querySelector('#guide-days').value);binding.focus=dialog.querySelector('#guide-focus').value;binding.autoUpdate=dialog.querySelector('#guide-auto').checked;binding.agentId=dialog.querySelector('#guide-agent').value;binding.gmail.labels=dialog.querySelector('#guide-labels').value.split(',').map(x=>x.trim()).filter(Boolean);binding.gmail.query=dialog.querySelector('#guide-query').value.trim();}
  if(step===4&&!state.pending){for(const p of edits){const field=dialog.querySelector(`[data-project="${CSS.escape(p.id)}"]`);if(field?.querySelector('[data-field="title"]')){p.title=field.querySelector('[data-field="title"]').value;p.objective=field.querySelector('[data-field="objective"]').value;p.client=field.querySelector('[data-field="client"]').value;}}}
 }
 function bindingFromCatalog(){const a=inventory.account;return {userId:a?.userId||'',organizationId:a?.organization.id||'',containers:[],artifacts:[],sessions:[],projects:(inventory.native?.projects||[]).slice(0,200).map(p=>p.id),tasks:[],agentId:inventory.native?.agents.find(a=>a.role==='Agente Ravi')?.id||'',gmail:{connectorId:'',account:'',labels:[],query:''},focus:'',days:15,autoUpdate:true};}
 function render(){
  const back=step>1?button('back','Voltar'):button('close','Agora não');
  if(step===1){const a=inventory?.account;
   draw(`<p class="guide-intro">Vamos encontrar seus projetos e reunir as informações que ajudam você a acompanhá-los.</p>${a?`<div class="guide-account"><span class="guide-orb" aria-hidden="true">${esc(a.organization.name.slice(0,1))}</span><div><strong>${esc(a.organization.name)}</strong><p>${esc(a.email||a.name)}</p><small>Organização confirmada pelo login do Ravi</small></div></div><p>Esta é a organização vinculada à CLI. Para usar outra, altere o login no Console e consulte novamente. Seus e-mails continuam sendo uma fonte pessoal.</p>`:'<div class="guide-empty"><h3>Entre para reconhecer sua organização</h3><p>O Ravi abre o login do Console no navegador. Depois de concluir, volte para confirmar a conexão.</p></div>'}<div class="guide-inline">${button('login',a?'Trocar login':'Entrar no Ravi')}${button('discover','Confirmar conexão')}</div>`,back+(state.projects.length?button('current','Revisar mapa atual'):'')+(a?button('next','Escolher fontes',true):''));
  }else if(step===2){
   draw(`<p class="guide-intro">Escolha o que pode ajudar a entender seu trabalho.</p><p>Os cadastros nativos disponíveis vêm selecionados; ajuste o que quer acompanhar. O levantamento consulta metadados. A análise lerá somente o conteúdo pertinente das fontes selecionadas. Pipeline, conversas e Gmail são opcionais.</p><label>Filtrar fontes por nome<input id="guide-filter" type="search" autocomplete="off"></label>${selection('Áreas da organização · artefatos e Pages',inventory.containers.map(x=>({...x,list:'containers'})),binding.containers)}${selection('Artefatos locais · escolha explícita',inventory.artifacts.map(x=>({...x,id:x.id.slice(9),list:'artifacts'})),binding.artifacts)}${['projects','sessions','tasks'].map(k=>selection({projects:'Cadastros de projetos',sessions:'Conversas e grupos',tasks:'Tasks'}[k],(inventory.native?.[k]||[]).map(x=>({...x,list:k})),binding[k])).join('')}<div class="guide-source guide-gmail"><h3>Gmail <span>Opcional</span></h3><p>Use e-mails como evidências de objetivos, decisões e próximos passos. O Workspace não envia nem altera mensagens.</p><label>Conexão Google<select id="guide-gmail"><option value="">Não usar agora</option>${inventory.connections.map(c=>`<option value="${esc(c.id)}" ${binding.gmail.connectorId===c.id?'selected':''}>${esc(c.name)} · ${esc(c.status)}</option>`).join('')}</select></label><label>E-mail da conta escolhida<input id="guide-account" type="email" value="${esc(binding.gmail.account)}" autocomplete="off"></label><label>Projeto do Console para a conexão<select id="guide-google-project">${inventory.containers.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select></label>${button('google','Conectar Google')}${button('discover','Atualizar conexões')}<small>Confira as permissões na tela do Google. Uma conexão nova só será usada depois que você selecioná-la e confirmar o recorte.</small></div><details class="guide-source"><summary>Fontes que não puderam ser consultadas</summary>${Object.entries(inventory.coverage).filter(([,s])=>s.status==='unavailable').map(([k])=>`<p>${esc(k)}: consulta indisponível. Você pode continuar com as demais.</p>`).join('')||'<p>As consultas ao catálogo foram concluídas.</p>'}</details>`,back+button('next','Definir contexto',true));
  }else if(step===3){
   draw(`<p class="guide-intro">Ajude seu Ravi a reconhecer o que pertence ao mesmo projeto.</p><label>O que você quer acompanhar?<textarea id="guide-focus" rows="4" maxlength="1200" placeholder="Descreva suas áreas, clientes ou iniciativas.">${esc(binding.focus)}</textarea></label><div class="guide-columns"><label>Janela inicial de mensagens<select id="guide-days">${[7,15,30,60,90].map(d=>`<option value="${d}" ${d===binding.days?'selected':''}>${d} dias</option>`).join('')}</select></label><label>Ravi que fará a análise<select id="guide-agent">${(inventory.native?.agents||[]).filter(a=>a.role==='Agente Ravi').map(a=>`<option value="${esc(a.id)}" ${a.id===binding.agentId?'selected':''}>${esc(a.name)}</option>`).join('')}</select></label></div><p>Documentos anteriores continuam úteis. Vários grupos podem alimentar um único projeto; trabalhos diferentes do mesmo cliente podem ficar separados.</p>${binding.gmail.connectorId?`<div class="guide-source"><h3>Recorte do Gmail</h3><label>IDs de marcadores, separados por vírgula<input id="guide-labels" value="${esc(binding.gmail.labels.join(','))}" autocomplete="off"></label><label>Filtro adicional de busca Gmail<input id="guide-query" value="${esc(binding.gmail.query)}" maxlength="500" autocomplete="off"></label><small>A janela selecionada é sempre aplicada. Até 80 mensagens por coleta; anexos não são lidos.</small></div>`:'<input id="guide-labels" type="hidden" value=""><input id="guide-query" type="hidden" value="">'}<label class="guide-choice"><input id="guide-auto" type="checkbox" ${binding.autoUpdate!==false?'checked':''}><span>Buscar mudanças a cada 15 minutos enquanto o Workspace estiver aberto e pedir a análise ao Ravi escolhido.</span></label><p>Você revisará o mapa encontrado antes de confirmar. Associações incertas permanecerão identificadas.</p>`,back+button('pause','Salvar e continuar depois')+button('map','Encontrar meus projetos',true));
  }else if(step===4){
   const p=state.pending;
   draw(p?`<div class="guide-empty"><span class="guide-orb" aria-hidden="true">↗</span><h3>${p.status==='ready'?'Evidências prontas para análise':p.status==='submitted'?'Seu Ravi recebeu a análise':'Análise ainda não confirmada'}</h3><p>${p.count} trechos no lote. A confirmação chega pelo resultado validado, não pela recência da conversa.</p><p>${p.status==='expired'?'O lote expirou; a última síntese continua preservada.':p.status==='submission_unconfirmed'?'Não foi possível confirmar o envio. Não repetiremos automaticamente.':''}</p>${p.status==='ready'?button('analyze','Analisar com meu Ravi',true):''}${button('refresh','Consultar resultado')}${['expired','submission_unconfirmed'].includes(p.status)?button('discard','Descartar lote e consultar de novo'):''}</div>`:`<p class="guide-intro">${edits.length?'Confira os projetos encontrados.':'Nenhum projeto confirmado pelas fontes selecionadas.'}</p><p>Edite nome e objetivo, una duplicatas ou separe frentes. Suas escolhas orientarão as próximas análises.</p><div class="guide-map">${edits.map(p=>`<article class="guide-project" data-project="${esc(p.id)}"><span class="guide-chip">${esc(p.client||'Iniciativa interna / cliente não confirmado')}</span><label>Projeto<input data-field="title" value="${esc(p.title)}" maxlength="200"></label><label>Cliente ou conta (opcional)<input data-field="client" value="${esc(p.client)}" maxlength="200"></label><label>Objetivo<textarea data-field="objective" rows="2" maxlength="1600">${esc(p.objective)}</textarea></label><p>${esc(p.summary)}</p><small>${p.evidence.length} fontes · ${esc(p.stage)}</small><div class="guide-inline"><select data-merge aria-label="Projeto de destino para unir"><option value="">Unir com…</option>${edits.filter(x=>x.id!==p.id).map(x=>`<option value="${esc(x.id)}">${esc(x.title)}</option>`).join('')}</select><button data-guide="merge" data-id="${esc(p.id)}">Unir</button><button data-guide="split" data-id="${esc(p.id)}">Separar fontes</button><button data-guide="exclude" data-id="${esc(p.id)}">Excluir do mapa</button></div></article>`).join('')}</div><p>${Object.values(state.coverage||{}).some(s=>s.status==='unavailable')?'Há fontes indisponíveis. O mapa cobre apenas o que foi possível consultar.':'A data da coleta e a data da síntese permanecem separadas.'}</p>`,button('close','Continuar depois')+(!p?button('confirm','Confirmar mapa',true):''));
  }else{
   draw(`<div class="guide-empty"><span class="guide-orb" aria-hidden="true">✓</span><h3>Seu contexto está salvo</h3><p>${state.projects.length} projetos no mapa da sua instalação.</p><p>As correções ficam registradas para as próximas análises. Em Configurar fontes você pode rever o recorte, consultar mudanças e ajustar o mapa.</p></div>`,button('advanced','Configurar outros widgets')+button('home','Abrir meu Workspace',true));
  }
 }
 async function open(){const n=++request;previousFocus=document.activeElement;step=1;draw('<p>Reconhecendo a instalação e consultando fontes disponíveis…</p>',button('close','Cancelar'));dialog.showModal();try{[state,inventory]=await Promise.all([api('view'),api('catalog')]);if(n!==request||!dialog.open)return;binding=structuredClone(state.draft?.binding||state.binding||bindingFromCatalog());step=state.pending?4:state.draft?.step||1;edits=structuredClone(state.projects);render();watch();}catch(e){notice(errors[e.message]||'Não foi possível consultar o Ravi. A configuração anterior foi preservada.',true);}}
 function watch(){clearInterval(poll);poll=setInterval(async()=>{if(!dialog.open||step!==4||!state?.pending||working)return;try{const v=await api('view');if(JSON.stringify(v.pending)!==JSON.stringify(state.pending)){state=v;edits=structuredClone(v.projects);render();}}catch{}},5000);}
 dialog.addEventListener('input',event=>{if(event.target.id==='guide-filter'){const q=event.target.value.toLocaleLowerCase();for(const el of dialog.querySelectorAll('.guide-choice'))el.hidden=!el.textContent.toLocaleLowerCase().includes(q);}});
 dialog.addEventListener('close',()=>{request++;clearInterval(poll);previousFocus?.focus({preventScroll:true});});
 document.addEventListener('click',event=>{if(event.target.closest('[data-action="setup"]')){event.preventDefault();event.stopImmediatePropagation();if(!dialog.open)open();}},true);
 dialog.addEventListener('click',async event=>{
  const c=event.target.closest('[data-guide]'),action=c?.dataset.guide;if(!action)return;
  if(action==='close'){dialog.close();return;}if(working)return;
  saveInputs();
  if(action==='current'){step=4;edits=structuredClone(state.projects);render();return;}
  if(action==='next'){step++;render();return;}if(action==='back'){step--;render();return;}
  if(action==='home'){location.hash='#/home';location.reload();return;}
  if(action==='advanced'){dialog.close();const b=document.createElement('button');b.dataset.action='setup-legacy';document.body.append(b);b.click();b.remove();return;}
  if(action==='exclude'){edits=edits.filter(p=>p.id!==c.dataset.id);render();return;}
  if(action==='merge'){const id=c.closest('[data-project]').querySelector('[data-merge]').value,a=edits.find(p=>p.id===c.dataset.id),b=edits.find(p=>p.id===id);if(!b){notice('Escolha o projeto que receberá as fontes.');return;}b.evidence=[...new Set([...b.evidence,...a.evidence])];b.gaps=[...new Set([...b.gaps,'Revise a síntese após unir as fontes.'])];edits=edits.filter(p=>p!==a);render();return;}
  if(action==='split'){const p=edits.find(p=>p.id===c.dataset.id);if(p.evidence.length<2){notice('Este projeto tem uma única fonte. Não há fontes suficientes para separar.');return;}
   const target=c.closest('[data-project]');target.innerHTML=`<h3>Escolha as fontes da nova frente</h3><p>As demais ficam no projeto atual. O novo nome e objetivo serão revisados em seguida.</p>${p.evidence.map(id=>`<label class="guide-choice"><input type="checkbox" data-split-source value="${esc(id)}"><span>${esc(state.sources?.find(s=>s.id===id)?.title||'Fonte sem título')}<small>${esc(state.sources?.find(s=>s.id===id)?.reviewNote||state.sources?.find(s=>s.id===id)?.limitation||id.split(':')[0])}</small></span></label>`).join('')}<button data-guide="split-save" data-id="${esc(p.id)}">Separar seleção</button>`;return;}
  if(action==='split-save'){const p=edits.find(p=>p.id===c.dataset.id),refs=[...c.closest('[data-project]').querySelectorAll('[data-split-source]:checked')].map(x=>x.value);if(!refs.length||refs.length===p.evidence.length){notice('Escolha parte das fontes para separar.');return;}p.evidence=p.evidence.filter(id=>!refs.includes(id));edits.push({...structuredClone(p),id:'user-'+crypto.randomUUID(),title:p.title+' · frente a revisar',summary:'Fontes separadas pelo usuário; síntese a revisar.',evidence:refs,gaps:['Definir o objetivo e revisar a síntese desta frente.']});render();return;}
  working=true;c.disabled=true;notice('Processando…');
  try{
   if(action==='discover'){inventory=await api('catalog');if(step===1)binding=structuredClone(state.binding||bindingFromCatalog());render();}
   if(action==='login'||action==='google'){const project=dialog.querySelector('#guide-google-project')?.value;await api(action,{project});notice('Conclua no navegador e use Confirmar conexão ou Atualizar conexões. O acesso ainda não está confirmado.');}
   if(action==='pause'){state=await api('draft',{revision:state.revision,draft:{step,binding}});dialog.close();}
   if(action==='map'){state=await api('bind',{revision:state.revision,binding});state=await api('collect');edits=structuredClone(state.projects);step=4;render();watch();}
   if(action==='analyze'){await api('analyze');state=await api('view');render();}
   if(action==='discard'){state=await api('discard',{revision:state.revision});state=await api('collect');render();}
   if(action==='refresh'){state=await api('view');edits=structuredClone(state.projects);render();}
   if(action==='confirm'){state=await api('review',{revision:state.revision,projects:edits});step=5;render();}
  }catch(e){notice(errors[e.message]||'Operação não concluída. A última configuração e síntese válidas foram preservadas.',true);}
  finally{working=false;c.disabled=false;}
 });
 let mapPolling=false,mapVersion='';try{mapVersion=JSON.stringify(JSON.parse(document.querySelector('#workspace-data').textContent).contextMap||null);}catch{}
 setInterval(async()=>{if(mapPolling||document.hidden||dialog.open)return;mapPolling=true;try{const map=await api('map'),version=JSON.stringify(map);if(version!==mapVersion){mapVersion=version;document.dispatchEvent(new CustomEvent('workspace-context-updated',{detail:map}));}}catch(e){if(['ORGANIZATION_CHANGED','CONSOLE_LOGIN_REQUIRED'].includes(e.message))location.reload();}finally{mapPolling=false;}},30000);
 if(location.hash==='#/setup'||window.workspaceSetupBootstrap?.firstRun)open();
})();
