(()=>{
 const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const stateLabels={ready:'Consulta confirmada',stale:'Versão anterior',unavailable:'Indisponível',not_configured:'Não configurada'};
 const sourceErrors={NO_AUTOMATIC_ADAPTER:'Sem atualização automática; data original mantida.',AUTH_EXPIRED:'O acesso expirou.',ACCESS_DENIED:'Acesso recusado.',ACCOUNT_MISMATCH:'A conta consultada difere da selecionada.',SOURCE_NOT_CONFIGURED:'Integração não configurada.',SOURCE_UNAVAILABLE:'A fonte não respondeu.',CREDENTIAL_UNAVAILABLE:'Acesso existente não disponível no Ravi.'};
 const labels={agenda:'Agenda do dia',meetings:'Reuniões · tl;dv',pipeline:'Pipeline revisado',agents:'Agentes e conversas',projects:'Projetos',tasks:'Tarefas',connections:'Estado das conexões',activity:'Atividade importada',alerts:'Alerts importados',projectAnalysis:'Análise revisada de projetos'};
 const dialog=document.createElement('dialog');dialog.className='setup-dialog';dialog.setAttribute('aria-labelledby','setup-title');document.body.append(dialog);
 let view,draft,focus,step=1;
 async function api(path,body={}){const r=await fetch('/setup/'+path,{method:'POST',headers:{'Content-Type':'application/json','X-Workspace-Setup':window.workspaceSetupNonce},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||'SOURCE_UNAVAILABLE');return data;}
 function status(message,error=false){const el=dialog.querySelector('.setup-status');el.textContent=message;el.classList.toggle('setup-error',error);}
 const errors={CONFIG_CHANGED:'A configuração mudou em outra janela. Feche e abra novamente.',INVENTORY_EXPIRED:'A consulta ficou antiga. Feche e abra novamente.',SESSION_AGENT_REQUIRED:'Inclua também o agente das conversas selecionadas.',EXPECTED_ACCOUNT_REQUIRED:'Informe a conta Google esperada para verificar a agenda.',SOURCE_CHANGE_REQUIRES_REVIEW:'Essa agenda já tem dados. A troca de conta exige revisão da fonte.',SETUP_BUSY:'Outra operação está em andamento. Aguarde.',SNAPSHOT_INSTALLATION_MISMATCH:'Esse arquivo pertence a outra instalação.',OLDER_SNAPSHOT:'O arquivo é anterior ao snapshot atual. A versão atual foi preservada.'};
 function shell(body,buttons){dialog.innerHTML=`<div class="setup-head"><div><small>Seu ambiente · ${step===1?'configuração':step===2?'revisão':'resultado'}</small><h2 id="setup-title">Configure seu Workspace</h2></div><button type="button" data-setup="close" aria-label="Fechar configuração">×</button></div><div class="setup-body">${body}<p class="setup-status" role="status" aria-live="polite"></p></div><div class="setup-actions">${buttons}</div>`;}
 const button=(action,label,primary=false)=>`<button type="button" data-setup="${action}" class="${primary?'setup-primary':''}">${label}</button>`;
 function check(name,id,label,selected,sub=''){return `<label class="setup-check"><input type="checkbox" data-selection="${esc(name)}" value="${esc(id)}" ${selected?'checked':''}><span>${esc(label)}${sub?`<small>${esc(sub)}</small>`:''}</span></label>`;}
 function form(){step=1;
  shell(`<h3>Uma Home com o seu contexto</h3><p>Escolha as fontes e os registros que quer acompanhar. A consulta respeita os acessos disponíveis no Ravi que está operando esta instalação.</p><div class="setup-fields"><label>Nome do workspace<input id="setup-name" maxlength="100" value="${esc(view.workspaceName)}"></label><label>Seu nome<input id="setup-owner" maxlength="80" value="${esc(view.ownerName)}"></label><label>Fuso horário<input id="setup-zone" value="${esc(view.timezone)}"></label><label>Janela de tarefas e reuniões<select id="setup-days">${[7,15,30,90].map(d=>`<option value="${d}" ${d===view.historyDays?'selected':''}>${d} dias</option>`).join('')}</select></label><label>Aparência inicial<select id="setup-theme">${['system','day','dark'].map(t=>`<option value="${t}" ${t===view.defaultTheme?'selected':''}>${{system:'Acompanhar sistema',day:'Day',dark:'Dark'}[t]}</option>`).join('')}</select></label></div><h3>Fontes da Home</h3><div class="setup-options">${Object.entries(labels).map(([k,v])=>check('sources',k,v,view.sources.includes(k),stateLabels[view.states[k]?.status]||'Não configurada')).join('')}</div><h3>Integrações opcionais</h3><div class="setup-fields"><label>Google Calendar<select id="setup-google"><option value="off">Não usar</option><option value="google-workspace" ${view.integrations.agenda.mode==='google-workspace'?'selected':''}>Acesso existente no Ravi</option></select></label><label>Conta Google esperada<input id="setup-account" type="email" value="${esc(view.integrations.agenda.account)}" autocomplete="off"></label><label>tl;dv<select id="setup-tldv"><option value="off">Não usar</option><option value="tldv" ${view.integrations.meetings.mode==='tldv'?'selected':''}>Chave existente no Ravi</option></select></label><label>Sites permitidos nos links (um por linha)<textarea id="setup-origins" rows="4">${esc(view.allowedOrigins.join('\n'))}</textarea></label></div><p>Nenhuma credencial passa por esta tela. Contas sem integração existente permanecem indisponíveis. Pipeline, temas e análises revisadas podem entrar por snapshot da própria instalação.</p>${['agents','sessions','projects','tasks'].map(kind=>`<h3>${{agents:'Agentes',sessions:'Conversas',projects:'Projetos',tasks:'Tarefas'}[kind]}</h3><p>${view.inventory.coverage[kind]?.status==='ready'?`${view.inventory[kind].length} registros no alcance visível. ${kind==='sessions'?'Somente metadados; este passo não lê mensagens.':''}`:'Consulta indisponível; isso não confirma ausência de registros.'}</p><div class="setup-options setup-records">${view.inventory[kind].map(r=>check(kind,r.id,r.title||r.name,view.selection[kind].includes(r.id),r.agent||r.source||r.status)).join('')||'<p>Nenhum registro disponível para selecionar.</p>'}</div>`).join('')}<p class="setup-alert">Salvar define sua seleção. O acesso às integrações só é confirmado ao consultar as fontes. Os widgets continuam personalizáveis na Home.</p>`,button('close','Cancelar')+button('review','Revisar seleção',true));
 }
 function readDraft(){const selected=k=>[...dialog.querySelectorAll(`[data-selection="${k}"]:checked`)].map(e=>e.value);const get=id=>dialog.querySelector('#setup-'+id).value;
  const selection={...view.selection};for(const k of ['agents','sessions','projects','tasks']){
   const displayed=new Set(view.inventory[k].map(r=>r.id));selection[k]=[...new Set([...view.selection[k].filter(id=>!displayed.has(id)),...selected(k)])];
  }
  return {revision:view.revision,workspaceName:get('name'),ownerName:get('owner'),timezone:get('zone'),historyDays:Number(get('days')),defaultTheme:get('theme'),allowedOrigins:get('origins').split(/\s+/).filter(Boolean),widgets:view.widgets,sources:selected('sources'),selection,integrations:{agenda:{mode:get('google'),account:get('account')},meetings:{mode:get('tldv')}}};
 }
 async function open(){focus=document.activeElement;step=1;shell('<p>Consultando os metadados disponíveis no seu Ravi…</p>',button('close','Cancelar'));dialog.showModal();
  try{view=await api('discover');if(dialog.open)form();}catch(e){if(dialog.open)status(errors[e.message]||'Não foi possível consultar o Ravi. A configuração foi preservada.',true);}
 }
 document.addEventListener('click',event=>{if(event.target.closest('[data-action="setup"]')){event.stopImmediatePropagation();open();}},true);
 dialog.addEventListener('close',()=>focus?.focus({preventScroll:true}));
 dialog.addEventListener('click',async event=>{
  const action=event.target.closest('[data-setup]')?.dataset.setup;if(!action)return;
  if(action==='close'){dialog.close();return;}
  if(action==='back'){if(draft)view={...view,...draft};form();return;}
  if(action==='review'){draft=readDraft();step=2;shell(`<div class="setup-review"><h3>${esc(draft.workspaceName)}</h3><p>${esc(draft.ownerName)} · ${esc(draft.timezone)} · ${draft.historyDays} dias</p><ul><li>${draft.sources.length} fontes selecionadas</li>${['agents','sessions','projects','tasks'].map(k=>`<li>${draft.selection[k].length} ${{agents:'agentes',sessions:'conversas',projects:'projetos',tasks:'tarefas'}[k]}</li>`).join('')}</ul><p>${draft.integrations.agenda.mode!=='off'?'Agenda: '+esc(draft.integrations.agenda.account):'Agenda não configurada'}</p><p>Esta confirmação salva apenas a configuração local. Nenhuma conta, permissão ou agendamento será alterado.</p></div>`,button('back','Voltar')+button('close','Cancelar')+button('save','Salvar configuração',true));return;}
  if(action==='home'){location.reload();return;}
  const control=event.target.closest('button');control.disabled=true;
  try{
   if(action==='save'){await api('save',draft);step=3;shell('<h3>Configuração salva</h3><p>A seleção está pronta. Consulte agora as fontes para confirmar o acesso e preencher a Home.</p><p>Para incluir pipeline ou análises revisadas, importe um snapshot desta instalação. O arquivo será validado antes de substituir os dados.</p><input class="setup-file" id="setup-import" type="file" accept="application/json,.json" aria-label="Snapshot da instalação">',button('import','Validar e importar')+button('home','Abrir Home')+button('collect','Consultar fontes',true));}
   if(action==='collect'){status('Consultando fontes selecionadas…');const result=await api('collect');shell(`<h3>${result.status==='collected'?'Consulta concluída':'Consulta indisponível'}</h3><p>Confira cada fonte. Dados anteriores são preservados quando uma consulta falha.</p><div class="setup-review">${Object.entries(result.results).map(([name,s])=>`<p><strong>${esc(labels[name])}</strong> · ${esc({ready:'Leitura confirmada',stale:'Última versão preservada',unavailable:'Indisponível'}[s.status]||s.status)}${s.error?`<br><small>${esc(sourceErrors[s.error]||'Consulta não confirmada; dados anteriores preservados.')}</small>`:''}</p>`).join('')}</div>`,button('home','Abrir Home',true));}
   if(action==='import'){const file=dialog.querySelector('#setup-import').files[0];if(!file||file.size>900000)throw Error('INVALID_IMPORT');await api('import',JSON.parse(await file.text()));status('Snapshot validado e importado. Abra a Home para ver os dados.');}
  }catch(e){status(errors[e.message]||'Operação não concluída. Confira a seleção e o formato dos dados; a última versão válida foi preservada.',true);}finally{control.disabled=false;}
 });
 if(location.hash==='#/setup')open();
})();
