  const sectionTitle=(eyebrow,title,action='')=>`<div class="section-heading"><div><p class="eyebrow">${e(eyebrow)}</p><h2>${e(title)}</h2></div>${action}</div>`;
  const sessionsFor=id=>data.sessions.filter(s=>s.agent===id);
  const workStatus=w=>label(w.status||'Estado não informado',w.status==='Para revisar'?'amber':'');
  const workRow=w=>link('/work/item/'+w.id,`<span class="work-icon">${icon('file')}</span><span class="work-row-copy"><h3>${e(w.name)}</h3><p>${e(w.description)}</p><span class="meta">${workStatus(w)}<span>${e(w.date)}</span></span></span>${icon('arrow')}`,'work-row');
  const sessionRow=s=>link('/sessions/'+s.id,`<span class="session-mark">${icon('review')}</span><span class="session-copy"><h3>${e(s.name)}</h3><p>${e(activityAgentName(s.agent))} · ${e(s.channel||'Conversa')}</p></span><span class="session-activity">${e(s.activityLabel)}<small>na captura</small></span>${icon('arrow')}`,'session-row');
  const sessionSection=id=>`<section class="session-section">${sectionTitle('Inventário autorizado','Conversas')}<p class="small muted capture-caption">${e(data.inventory.capturedLabel)}. Recência não comprova execução.</p><div class="panel session-list">${sessionsFor(id).map(sessionRow).join('')||'<p>Nenhuma conversa incluída neste recorte.</p>'}</div></section>`;
  function work(){return `${heading('Trabalho','Projetos, andamento e próximos passos.','Seu workspace')}${activityData?activityOverview():''}<section>${sectionTitle('Contexto','Projetos',link('/portfolio','Ver todos'))}<div class="native-list">${projectItems().slice(0,5).map(contextProjectRow).join('')||unavailableNative('projects')}</div></section><section class="native-section-title">${sectionTitle('Ravi Tasks','Trabalhos acompanhados')}${activityData?activityWorkList():`<div class="native-list">${homeData.tasks.map(t=>link('/tasks/'+t.id,`<span><h2>${e(t.title)}</h2><p>${e(taskLabel(t))}</p></span>${icon('arrow')}`,'native-row')).join('')||unavailableNative('tasks')}</div>`}</section>${data.work.length?`<section class="native-section-title">${sectionTitle('Fontes incluídas','Registros documentados')}<div class="panel work-list">${data.work.map(workRow).join('')}</div></section>`:''}`;}
  function project(){return portfolio();}
  function workDetail(id){const w=data.work.find(w=>w.id===id);if(!w)return missing();return `${back('/work')}${heading(w.name,w.description,w.kind)}<section class="panel">${workStatus(w)}<p class="small muted">${e(w.date)}</p><p>${e(w.meaning)}</p><ul>${(w.facts||[]).map(f=>`<li>${e(f)}</li>`).join('')}</ul>${w.next?`<h2>Próximo passo registrado</h2><p>${e(w.next)}</p>`:''}${sourceLinks([w.source])}</section>`;}
  function agents(params){const showSessions=params.get('view')==='sessions';return `${heading('Agentes','Quem participa das suas conversas e frentes de trabalho.','Seu workspace')}${nativeLiveNotice('agents')}${data.agents.length&&activityData?activityOverview():''}<div class="inventory-controls"><div class="inventory-tabs">${link('/agents','Agentes',`inventory-tab ${!showSessions?'selected':''}`)}${link('/agents?view=sessions','Conversas',`inventory-tab ${showSessions?'selected':''}`)}</div><span class="small muted">${e(data.inventory.capturedLabel)}</span></div>${!data.agents.length?`<section class="panel">${unavailableNative('agents')}</section>`:showSessions?`<div class="panel session-list">${data.sessions.map(sessionRow).join('')}</div>`:`<div class="inventory-grid">${data.agents.map(a=>`<article class="panel inventory-agent" data-agent-id="${e(a.id)}"><div class="agent-overview"><span class="avatar">${e(a.name.slice(0,1))}</span><div><h2>${e(a.name)}</h2><p>${e(a.role||'Agente do workspace')}</p></div></div>${activityBadge(a.id)}<p class="small muted">${sessionsFor(a.id).length} conversas incluídas</p>${link('/agents/'+a.id,`Acompanhar ${icon('arrow')}`)}</article>`).join('')}</div>`}`;}
  function agent(id){return activityAgentPage(id);}
  function session(id){const s=data.sessions.find(s=>s.id===id);if(!s)return missing();return `${back('/agents?view=sessions')}${heading(s.name,'Conversa incluída no inventário desta instalação.',s.channel||'Conversa')}<section class="panel"><h2>Agente relacionado</h2>${link('/agents/'+s.agent,activityAgentName(s.agent))}<dl class="work-metadata"><div><dt>Atividade na captura</dt><dd>${e(s.activityLabel)}</dd></div><div><dt>Consulta</dt><dd>${e(data.inventory.capturedLabel)}</dd></div></dl><div class="dialog-note">A recência da conversa não prova execução. O conteúdo integral não está incluído nesta interface.</div></section>`;}
  function review(){return `${back('/home')}${heading('Organize seu workspace','Escolha o que faz sentido para o seu dia.')}<section class="panel"><h2>Home</h2><p>Escolha widgets, tamanho e ordem. As fontes disponíveis dependem da configuração da sua instalação.</p><button class="primary" data-action="home-customize">Personalizar Home</button></section><section class="panel"><h2>Contexto</h2><p>Projetos, agentes, trabalhos e fontes preservam seus vínculos e datas.</p>${link('/work','Percorrer o trabalho')}</section>`;}
